### ISSUE TITLE
Python script wont launch

### ISSUE THREAD

**Issue by Rejectfurries** [iholston/lol-bot#102]
![image](https://github.com/iholston/lol-bot/assets/147285171/ecac8a69-1539-4ed3-88f2-1fab00e1993e)
I try use the script once i do the installer this pops up and nothing happens. Im not sure what the hell im doing. I just need some help.f

**Comment by iholston** [comment]
You should download the latest release instead of cloning the repository

**Comment by LSTMPD** [comment]
I had this problem too, the issue was with dearpygui not being out for Python 3.12 yet. However, as of today, I can see a '.github' file being edited in their repo yesterday, including 3.12 support. My safest bet was using 3.11, but it's possible their push fixed the issue.

**Comment by iholston** [comment]
Once I'm finished building out the gui and it is stable il do a new release and update the Readme with instructions on how to set it up. Until then the latest release is stable
