### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by Borgi3** [iholston/lol-bot#106]
Hey, great script thanks. Was working few weeks ago, but when im trying it now (1.3.2 version due to no "launcher") I get this error:

  File "C:\Users\XXX\Downloads\lol-bot-1.3.2\lol-bot-1.3.2\scripts\client.py", line 74
    match self.get_phase():
          ^
SyntaxError: invalid syntax

Im very new to python. Can you please help me out abit?

**Comment by iholston** [comment]
You probably need to update ur python to a version later than 3.10
