### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Only34** [iholston/lol-bot#108]
Hello. I wanna contact you. You have a discord?

**Comment by iholston** [comment]
Negative, if you have any ideas or issues I respond regularly here.

**Comment by Only34** [comment]
I'm trying to find a way to open multiple League of Legends (game itself. not just a client) Then I can use your bot to level more than one account in the pc. I know vm is exist but it's detected by riot right now. I found few website forum talking about this. I'm not a good in this coding stuffs that's why I thought may you can take a look.

**Comment by iholston** [comment]
It's just not possible to do as far as I know. VMs are the only way to have multiple bots running on a single computer.

**Comment by Only34** [comment]
Actually it's possible as I can see today on the internet. Also I saw some guy at Aurora Bot Discord server. He sent a screenshot and I could see multiple league of legends. Then I talked him at private and of course he didn't gave me a solution. I mean there is a probably a solution exist waiting to solve.

**Comment by iholston** [comment]
It may be possible, from what iv seen you can't do it but if someone else can then they should make a fork of the repo and modify it to accommodate multiple league of legends instances.
