### ISSUE TITLE
Adjustment of click coordinates

### ISSUE THREAD

**Issue by damare1** [iholston/lol-bot#109]
Hello.
When clicking on the mini-map, it is slightly out of alignment and I would like to adjust it.
How can I do this?
At first the bot goes into the middle, but I would like it to go a little deeper.

**Comment by iholston** [comment]
The coordinates are in the constants.py, you can use the ratio builder to find new coordinates and change them in the constants.py file.

**Comment by damare1** [comment]
thank you
