### ISSUE TITLE
Set Game Mode to Intro Bots

### ISSUE THREAD

**Issue by Mewspoop1** [iholston/lol-bot#11]
Hey, I was just wondering how I can change the game mode from Beginner bots to Intro bots. There are alot more "people" and less bots in beginner than in intro, so I feel it will be safer. I tried changing it myself, but I have 0 experience coding and it didn't do anything. Any help would be awesome!

**Comment by iholston** [comment]
To change the game mode from beginner to intro simply change line 32 in constants.py from 'GAME_LOBBY_ID = BEGINNER_BOTS_GAME_LOBBY_ID' to 'GAME_LOBBY_ID = INTERMEDIATE_BOTS_GAME_LOBBY_ID'

**Comment by iholston** [comment]
right click on it and try and open it in notepad

**Comment by Mewspoop1** [comment]
Oh awesome! Thanks so much! 

and to be certain this changes it to intro bots, not intermediate right? I just ask because I see "intermediate" in the line of code. 

Thanks for being so patient!

**Comment by iholston** [comment]
my apologies, that will create an intermediate game. If you want to create an intro game lobby change line 32 in constants.py from 'GAME_LOBBY_ID = BEGINNER_BOTS_GAME_LOBBY_ID' to 'GAME_LOBBY_ID = 830'. 830 is the id for intro bots. 

Intro bots is typically only filled with other bots which can lead to longer game times than beginner games and sometimes even losses, but there should be no issue overall.

**Comment by Mewspoop1** [comment]
Awesome! Thank you so much!

**Comment by Mewspoop1** [comment]
One more question! How can I change the champion it picks? Currently it picks Ahri 99% of the time, and the 1% is Ziggs.

**Comment by iholston** [comment]
In constants.py, line 36, you can add or remove champion numbers to the array and the bot will attempt to select them first.

If you do not have the champion or they are all picked by other players the bot will then pick a free to play champion.

**Comment by Mewspoop1** [comment]
Okay, is there a list with what numbers correlate with what champions
somewhere?

**Comment by iholston** [comment]
the first google search i did lead to https://github.com/ngryman/lol-champions/blob/master/champions.json, you should be able to find the champ ur looking for and then use the "key" value in the array. this particular list is old though so it won't have some champs.
