### ISSUE TITLE
A lot of issues.

### ISSUE THREAD

**Issue by AantosS** [iholston/lol-bot#113]
1. My game starts running in 1024x768, there is no 1024x720 resolution in settings. So bot just goes some random places. 
2. I didnt mess with game.cfg or persisted settings file,
3. BOT ui troubles: stop bot button doesnt work, restart UX doesnt work (no logs written at all), close client button doesnt work, didnt mess with code tho, downloaded several times, nothing chamged. 
4. Discovering other issues, i dont see in my files persistedsettings.json. Is this normal?

**Comment by iholston** [comment]
Yes, at the moment. The latest release is stable and is what you should use. The GUI is in beta and is only out for testing atm.
