### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by CarouselV** [iholston/lol-bot#114]
Hello, can someone please guide me on how to install it? I downloaded Python and installed it where I wanted it to be then I ran the installer.bat and it downloaded some stuff and that's it, how can I find the launcher and any other files and where are the rest of the bot files on the thread for me to download, I'm new to this sorry.

**Comment by hubman-star** [comment]
latest release: launcher.bat in root directory; resources in resources folder, scripts in scripts folder
source version: main.pyw in root directory; resources in app/resources folder, scripts in app/bot and app/common folders, gui in app/gui folder

**Comment by iholston** [comment]
If you download the latest release you will have the launcher.bat, if you clone the repo you just need to double click on main.pyw

**Comment by CarouselV** [comment]
I downloaded the latest release file which is v1.3.2 and extracted it in the Python file and whenever I click on the launcher it says Python not found press any key to continue then it closes the window right after

**Comment by iholston** [comment]
are you sure that you checked the button that says "add to path"?

**Comment by iholston** [comment]
There is now a .exe that you can simply download and run without python or any dependencies. @CarouselV
