### ISSUE TITLE
Need help launching 

### ISSUE THREAD

**Issue by BRebbi** [iholston/lol-bot#121]
Sorry for wasting your time but i just cant make it work. I basically did everything there was supposed to be done. Installed the requirements, python set up, right lol path. However i dont know why when i start launcher.bat it shows this: 
![image](https://github.com/iholston/lol-bot/assets/103070763/e26ef48c-ba40-41d7-95e7-4abea2f2f60d)
As i understand from the code its supposed to create a "logs" directory in the bot directory (I might be wrong). I thought it could be related to administrator permissions but i doubt it. Anyways, i proceeded to create manually a logs folder and then ran the launcher.bat file.
![image](https://github.com/iholston/lol-bot/assets/103070763/bb47d278-7c06-4ac5-810f-fe964eb973e6)
![image](https://github.com/iholston/lol-bot/assets/103070763/c4acd500-7c7d-4603-9e74-aadcbd314d0b)
I might have gotten this totally wrong tho...
If you ve got any idea what i did wrong please let me know.

**Comment by iholston** [comment]
try running the launcher as admin

**Comment by BRebbi** [comment]
Man im just dumb. Everything is fine it just had to be in a folder other than users. Changed the location it works perfectly. Thanks again and sorry for the dumb question :)
