### ISSUE TITLE
Early/Mid Game Timers

### ISSUE THREAD

**Issue by MasterBougli** [iholston/lol-bot#123]
Hi . I have some issues with your bot :
-It stay stuck in Early game so after 6min when the first turret is distroy it stay in mid and do nothing
-It use Flash at spawn with no reason 
-Buy item didn't work with other language than English

**Comment by iholston** [comment]
The bot does not push beyond mid before 10 min 30 seconds, the bought uses abilities completely randomly, and we will be fixing the language issue soon.

**Comment by iholston** [comment]
In the meantime, v1.2.1 will be able to buy items with any language.
