### ISSUE TITLE
I Want to Adjust the Bot's Automation

### ISSUE THREAD

**Issue by MarsUnrankedShop35** [iholston/lol-bot#124]
I want to make edits inside the bot. I want it to kill the dragon, but I couldn't do it.

**Comment by iholston** [comment]
That would be a little bit of work but you are more than welcome to make a fork of the repo and implement it!

**Comment by MarsUnrankedShop35** [comment]
Can you please help me via Discord?
Discord: marsunrankedshop

**Comment by iholston** [comment]
Unfortunately, at this time I'm not on discord. I will not be able to implement this feature but if you want to get started the best place to start is in the game.py file. you should be able to use the ratio builder that is included in v1.3.2 and prior to get in game ratios and try and make the bots kill drag.

**Comment by MarsUnrankedShop35** [comment]
constanst.py

# GAME BUTTON RATIOS
GAME_MINI_MAP_UNDER_TURRET = (0.8760, 0.8846)
GAME_MINI_MAP_CENTER_MID = (0.8981, 0.8674)
GAME_MINI_MAP_ENEMY_NEXUS = (0.9628, 0.7852)
GAME_ULT_RATIO = (0.7298, 0.2689)
GAME_AFK_OK_RATIO = (0.4981, 0.4647)
GAME_CENTER_OF_SCREEN = (0.5, 0.5)
GAME_SYSTEM_MENU_X = (0.7729, 0.2488)
DRAGON_KILL_POSITION = (0.8000, 0.8000)
BASE_RETURN_POSITION = (0.2000, 0.2000)

I would need more specific information on which command line to add the code to inside 'game.py'.

**Comment by iholston** [comment]
Yea so you would need to talk with someone else who knows how to code in order to do it.
