### ISSUE TITLE
Does not reconnect to the match

### ISSUE THREAD

**Issue by Aeikir** [iholston/lol-bot#13]
The bot works for a couple of games but whenever it disconnects from the match for whatever reason it does not reconnect back and gets stuck.

This is the error: 
![vmconnect_oKwXkOyITD](https://github.com/iholston/lol-bot/assets/132776640/ae896f44-1058-4b18-acef-b242bc624f1c)

**Comment by iholston** [comment]
I believe this issue should be resolved. But I'll leave this open for a while just incase you have this issue again.

**Comment by Aeikir** [comment]
I am getting this error now once the loading screen ends and the game starts:
![vmconnect_GJKwZkkKpu](https://github.com/iholston/lol-bot/assets/132776640/266e7306-0d69-4494-b1c8-7f68bbd4f1b6)

**Comment by iholston** [comment]
Right so this looks like the original issue from #8. If you could comment out line 12 in bot.py and uncomment line 13 and then run the bot, it will add a log file to your desktop. When this issue happens again drop that log file in here so I can better work on this issue.

**Comment by Aeikir** [comment]
[log.txt](https://github.com/iholston/lol-bot/files/11559001/log.txt)

Here is the log file, thanks for your help

**Comment by iholston** [comment]
should be fixed now. drop log files if you get more errors related to this.

**Comment by Aeikir** [comment]
Now it keeps closing the league process while in the loading screen it cant get into a game
But i figured out the cause of it,  it happens when i use an FPS Limiter to limit the fps to 10 or below ( to save cpu usage )
im not sure how to fix it

**Comment by iholston** [comment]
So ur saying that it works normally unless you use the fps limiter?

**Comment by Aeikir** [comment]
Yeah i dont know why thats the case

**Comment by iholston** [comment]
Yea so that issue is not related to the league bot, and thus I can't really help you unfortunately. Since it looks like the original issue has been fixed I will be closing this issue.
