### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by bzyqdejv** [iholston/lol-bot#133]
![image](https://github.com/iholston/lol-bot/assets/108908222/d0d5205d-8634-4cf0-a12a-889d32e0d756)

**Comment by iholston** [comment]
Try downloading and running v2.0.1 and see if this issue persists.

**Comment by iholston** [comment]
Has this issue been resolved?

**Comment by bzyqdejv** [comment]
![image](https://github.com/iholston/lol-bot/assets/108908222/a63fcb8b-f2ba-4a9d-9ed3-058c0fc0c397)
Unfortunately, I have the same problem with the new package, can you help somehow, it's making an error somewhere

**Comment by bzyqdejv** [comment]
![image](https://github.com/iholston/lol-bot/assets/108908222/97cebce3-c85f-46d2-b11d-54d2a9ce1b34)
I think that's why I've tried a lot but unfortunately I get the same error

**Comment by iholston** [comment]
Try moving the script to your desktop. C:\user\desktop\lol-bot-2.0.1 and run it from there
