### ISSUE TITLE
Bug in game?

### ISSUE THREAD

**Issue by Borgi3** [iholston/lol-bot#134]
Hey,

Nice bot, used it for almost one account now (lvl 24). But now the recent days the champ has started to go to blue buff and just stay afk between mid and top. I have reinstalled and updated the script, but still happening. I get lvl 1-3 each game. 

Know how to fix?

**Comment by iholston** [comment]
Sounds like the minimap scaling is off, is the screen opening in a 1024x768 window?

**Comment by Borgi3** [comment]
You are exactly right. It was 1024x768 (it gets that automatically), but the minimap was lower ingame. Had to adjust it to 40 ish and now its working. Thanks alot
