### ISSUE TITLE
Problem with the loop

### ISSUE THREAD

**Issue by dimondduck123** [iholston/lol-bot#135]
![Screenshot_16](https://github.com/iholston/lol-bot/assets/149424210/04fe2002-d2a4-4eca-a128-78429032fbad)

Place the game on D disk 
He plays on one account and stops and does not continue after that

**Comment by dimondduck123** [comment]
i have last virsion

**Comment by iholston** [comment]
Not sure what the problem could be here. does restarting the app work?

**Comment by dimondduck123** [comment]
I saw that the program was working normally, but I wanted to open more than one client, so I wrote. The important thing is that the program no longer works after the first account. I need to press the Start button again, so I do not know whether this is the reason or not.

**Comment by iholston** [comment]
Well in that case, I cannot really help you since something that you changed is now causing an issue. Best of luck though!
