### ISSUE TITLE
The bot became detectable?

### ISSUE THREAD

**Issue by Kenry26** [iholston/lol-bot#137]
i got banned 
Bot used over VMware

![Banned](https://github.com/iholston/lol-bot/assets/71223909/95d3e8fc-a270-43ce-843a-4362682b6e70)

**Comment by jinxx0** [comment]
vmware detected

**Comment by iholston** [comment]
Most likely detected that you were running in a vm and banned you because of that. Though its not possible to tell exactly why you were banned.
