### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by qualidey** [iholston/lol-bot#14]
![изображение](https://github.com/iholston/lol-bot/assets/70530996/aa3b8f68-a0de-4ad9-a44e-1d3b833429bc)

**Comment by iholston** [comment]
Make sure ur using python 3.10 or later

**Comment by iholston** [comment]
to be a little more specific, you need to make sure that if you open cmd, and type 'python --version' that it states python 3.10 or greater. if it says something like python 3.9.X or less you need to update python to a later version.
