### ISSUE TITLE
I don't know how to write the code in cmd

### ISSUE THREAD

**Issue by Shieldstrike** [iholston/lol-bot#140]
Help please, I'm stupid.
![image](https://github.com/iholston/lol-bot/assets/151389624/ebb28df5-fd01-4a0e-b241-93993ce63943)

**Comment by iholston** [comment]
You are doing it correctly, reopen the python installer and make sure that pip is checked. It should install pip for you.

**Comment by iholston** [comment]
Your issue is that you have python installed but don't have pip installed so once you fix that you can run the command.

**Comment by Shieldstrike** [comment]
![image](https://github.com/iholston/lol-bot/assets/151389624/08072e68-787e-4a2b-a18c-3f128116cc48)
![image](https://github.com/iholston/lol-bot/assets/151389624/58568b89-d431-49d6-a179-cbcc8a5ca0e4)
![image](https://github.com/iholston/lol-bot/assets/151389624/0cf691e4-3110-4c46-a262-9861028e025e)
![image](https://github.com/iholston/lol-bot/assets/151389624/92629ecd-8ede-442f-adf3-e65d494060ba)

**Comment by Shieldstrike** [comment]
Well...

**Comment by Shieldstrike** [comment]
What do I do now?

**Comment by iholston** [comment]
Try installing it for all users, and make sure to restart cmd afterwards

**Comment by Shieldstrike** [comment]
![image](https://github.com/iholston/lol-bot/assets/151389624/2980f3a9-ad1f-43a0-8da0-9df4f610f2d9)
I can't download it for all users, I don't know why and I've already looked on the internet

**Comment by Shieldstrike** [comment]
I've already run the file as an administrator, I've already accessed the properties and I can't

**Comment by Shieldstrike** [comment]
What do I do now?

**Comment by iholston** [comment]
I'm not really sure what to tell you at this point, you simply need to figure out how to install pip on your computer. Once you do that, you should be good to go.
