### ISSUE TITLE
BOT stops occasionally.

### ISSUE THREAD

**Issue by damare1** [iholston/lol-bot#141]
Occasionally an error appears and the bot stops as shown in the image.
Is there a solution?
![wa](https://github.com/iholston/lol-bot/assets/144917228/e8eb21e7-2000-446c-b9d8-0af7d56759dd)
Log file
[dotup.org3085729.log](https://github.com/iholston/lol-bot/files/13403553/dotup.org3085729.log)

**Comment by iholston** [comment]
Thanks for the log file, this is a bug. I will get a fix out for it in the next release 👍
