### ISSUE TITLE
it doesnt open/work

### ISSUE THREAD

**Issue by sibrag** [iholston/lol-bot#142]
as the title says, its there a way i can contact u or someone can help with me this ?

**Comment by iholston** [comment]
Did you follow the instructions in the readme

**Comment by Samigulla** [comment]
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by iholston** [comment]
you need to install the required pip modules, as listed in the readme. run 'pip install -r requirements.txt' in cmd
