### ISSUE TITLE
Bot isnt farming

### ISSUE THREAD

**Issue by milkmanrave** [iholston/lol-bot#145]
Hey, the bot will start by buying cule / d blade. But once it arrives under mid turret, it just stop moving, u can see it's clicking, but always on the same spot. I didnt touch a single bind (except muted sound). Not sure what i did wrong (I followed the readme, installed the requirements). 
I tried twice, but always the same problem.

Thanks for ur help and time. :p
[21112023_1502.log](https://github.com/iholston/lol-bot/files/13427352/21112023_1502.log)
[21112023_1453.log](https://github.com/iholston/lol-bot/files/13427353/21112023_1453.log)

**Comment by iholston** [comment]
This is an issue that will hopefully be addressed in a future release. But if you have minimal movement off or attack move off then the bot can move. I would suggest trying to entirely reset your league settings and the issue should resolve itself.

**Comment by iholston** [comment]
This should be resolved in the latest release.
