### ISSUE TITLE
Cant Start Bot

### ISSUE THREAD

**Issue by AtlasSchlumpf** [iholston/lol-bot#147]
It says League Installation Path is unvalid. Update Path

**Comment by iholston** [comment]
You need to update the path to your league of legends install. the regular C:/Riot Games/League of Legends path is not correct

**Comment by VISITMYASS** [comment]
What's the correct path? I don't have a league launcher anymore only riotclientservices

**Comment by iholston** [comment]
@VISITMYASS you need to find wherever league of legends is installed on your computer typically its  C:/Riot Games/League of Legends but if its somewhere else that is what you need to put for the path
