### ISSUE TITLE
For some reason the bot only buys Cull

### ISSUE THREAD

**Issue by GorillaShake** [iholston/lol-bot#153]
![IMG_20231125_094543.jpg](https://github.com/iholston/lol-bot/assets/151993172/f8abcfa5-4b65-47c3-99ad-af29c86029fe)

**Comment by GorillaShake** [comment]
Doesn't buy items unless I buy them ![IMG_20231125_131403.jpg](https://github.com/iholston/lol-bot/assets/151993172/bb84175c-1dfa-4065-a751-73aa7adc141e)

**Comment by GorillaShake** [comment]
![IMG-20231125-WA0007.jpg](https://github.com/iholston/lol-bot/assets/151993172/f2c247a1-481c-4b74-ae6c-29f53c591b47)

It either Cull or doesn't buy anything after the starter item

**Comment by iholston** [comment]
Closing this to #146
