### ISSUE TITLE
League Detection

### ISSUE THREAD

**Issue by sonicwil** [iholston/lol-bot#155]
![image](https://github.com/iholston/lol-bot/assets/140975550/301a197f-b7ea-44e7-a0a5-808430186f2b)
Currently I see that the bot detects the league that is running through the manager, right? I would like some help so that the bot can detect the league, but first check the account of the computer that is logged in, for example in the image account 1 and perfi. Because he is currently accessing the league data from the other account

**Comment by iholston** [comment]
The bot does not support multiple league instances running on a single computer. And off the top of my head I'm not sure of a good solution for this particular issue

**Comment by QuePast** [comment]
I think lcu stops working with second client and it's always connected to one when I was testing allow multiple clients attribute. I wasn't digging too much into it. Maybe the connection is switched into another port
