### ISSUE TITLE
Unknown Error: No Account Added

### ISSUE THREAD

**Issue by moatasem2002** [iholston/lol-bot#156]
hi sir can you help me please .. first of all i am zero at programing so i just dont know what you are saying about this error and i dont know how to fix it XD so can i download anydesk and you fix it to me please ?? because i really dont know anything from what you are saying but i just downloaded the python and all things you required it .

![Screenshot (1)](https://github.com/iholston/lol-bot/assets/152172656/682f017d-37a2-4bed-b485-2263d538ab2c)

**Comment by iholston** [comment]
This is actually a bug that will be fixed, but in the meantime, just add an account on the accounts page and it should solve the issue.

**Comment by iholston** [comment]
This has been addressed in the latest version. If you still have any issues let me know.
