### ISSUE TITLE
BOT stops sometimes.

### ISSUE THREAD

**Issue by damare1** [iholston/lol-bot#159]
![a](https://github.com/iholston/lol-bot/assets/144917228/56f3970a-5d66-411d-9956-bc13b278daf6)
ver2.1.3
BOT stops sometimes.
It crashes and the client closes.
[log.txt](https://github.com/iholston/lol-bot/files/13521172/log.txt)

**Comment by anaquierealgo** [comment]
Do you use the bot in a virtual machine?

**Comment by damare1** [comment]
No

**Comment by damare1** [comment]
I do not tamper with the Account tab and only click on Start Bot to use it.
Due to the frequency of occurrence, we are now using ver 2.0.0.
It does not occur with ver2.0.0.
Do you know the cause?
It occurred before. Log file
[02122023_0011.log](https://github.com/iholston/lol-bot/files/13533209/02122023_0011.log)

**Comment by iholston** [comment]
yes, the issue is that you have an invalid username or password. The bot cannot log into league of legends because you have to add accounts to the account tab

**Comment by damare1** [comment]
On the "Account" tab, do I need to enter the login ID and password I use for botting?
