### ISSUE TITLE
Bot gets stuck after some time

### ISSUE THREAD

**Issue by Aeikir** [iholston/lol-bot#16]
It works but after some time it gets stuck at "Skip waiting for stats" screen.
 
![skipstats](https://github.com/iholston/lol-bot/assets/132776640/7f6bbb18-4520-46b5-a853-f7902a573ebe)

[log.txt](https://github.com/iholston/lol-bot/files/11578813/log.txt)

**Comment by iholston** [comment]
thanks for the log file. i need to update the connection error-out times for slower connections.
