### ISSUE TITLE
I cannot open main.pyw

### ISSUE THREAD

**Issue by damare1** [iholston/lol-bot#165]
I have purchased a new laptop.OS is Windows 10.
I installed python 3.12.1 and the Microsoft C and C++ (MSVC) runtime library(https://aka.ms/vs/17/release/vc_redist.x64.exe), but I cannot open main.pyw.
![da](https://github.com/iholston/lol-bot/assets/144917228/7be2c0d1-d091-4add-a75a-2c5f55f93801)
cd C:\Users\user\Desktop\lol-bot-2.2.2
python main.pyw
After entering the above, I got this message. Do you know how to resolve this?

**Comment by iholston** [comment]
did you run 'pip install -r requirements.txt' ?

**Comment by damare1** [comment]
No, I don't. How do you do it?
