### ISSUE TITLE
Which program should I use to run the LoL-Bot on a virtual computer?

### ISSUE THREAD

**Issue by sefaksoy** [iholston/lol-bot#166]
**Describe the solution you'd like**

Hello, I am currently running the bot on my own computer via a Hyper-V virtual machine. But I think Hyper-V technology consumes too much RAM, GPU and CPU. The VMware program was banned with the latest patches for LoL. Is there a program you can recommend?

**Version**
What version of the lol-bot are you running?
Latest

**Additional context**

Thanks for bot!!

**Comment by iholston** [comment]
I personally do not run the bots in a VM so I do not have any recommendations. I'll leave this thread open though in case anyone else has a solution. Glad you are enjoying the bot.

**Comment by thearmytr** [comment]
When I want to run LoL via VMware, I get the following error. Is there any chance you can research this issue and share information with us?
![Screenshot_1](https://github.com/iholston/lol-bot/assets/44275750/1ab63328-cba9-4936-ab88-2d6cd0d530ba)

**Comment by iholston** [comment]
No, unfortunately I will not be fixing VM issues.

**Comment by ericshug** [comment]
they will ban VM account ,dont waste time to try.

**Comment by thearmytr** [comment]
> they will ban VM account ,dont waste time to try.

Do you know any other way to run the LoL client?
