### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by faroldelua** [iholston/lol-bot#167]
When i try to open the .exe this error happens.

I have Python and Microsoft Visual C++  installed alredy.
![NVIDIA_Share_01bEltUXNI](https://github.com/iholston/lol-bot/assets/109042993/21e967a3-d557-47d6-a192-2e2cdb01354e)

**Comment by iholston** [comment]
Which operating system are you on? The script unfortunately only works on Windows 10 and Windows 11.

**Comment by faroldelua** [comment]
> Which operating system are you on? The script unfortunately only works on Windows 10 and Windows 11.

Windows 10

**Comment by ericshug** [comment]
Windows 10,same today.

**Comment by faroldelua** [comment]
> I'll look into it this week. Does this happen every single time?

All the time i run the .exe

**Comment by iholston** [comment]
Can you paste all the text from the error in here? @faroldelua
