### ISSUE TITLE
v2.2.2 Stops on error

### ISSUE THREAD

**Issue by damare1** [iholston/lol-bot#169]
Hello.
I just checked and it stopped with an error, so I am reporting it.
![q](https://github.com/iholston/lol-bot/assets/144917228/19a0d5f0-d3ff-471b-b562-73e32ed112c2)
log file
[11122023_2346.txt](https://github.com/iholston/lol-bot/files/13643220/11122023_2346.txt)

**Comment by joe5050** [comment]
Me too

**Comment by iholston** [comment]
Thanks for the report. I should be able to get a fix this week.
