### ISSUE TITLE
It did go afk many times

### ISSUE THREAD

**Issue by joe5050** [iholston/lol-bot#170]
**Describe the bug**

**Version**
What version of the lol-bot are you running?

**Screenshots**

**Log Files**
If applicable, add the log file containing the error messages from your issue

**Additional context**

**Comment by iholston** [comment]
Are you running the bot in a VM? You should ensure that the clicks within the game are working. Is the bot buying items?

**Comment by joe5050** [comment]
The PC without mouse and keyboard is that the problem ?

**Comment by iholston** [comment]
In some cases, not having a mouse plugged in can cause the bot clicks to fail. You don't need a keyboard, but try plugging in a mouse and see if you still have the same issue.

**Comment by joe5050** [comment]
Oki thanks

**Comment by elfenick** [comment]
Did you fix it? i have same issue

**Comment by iholston** [comment]
make sure you have a mouse plugged in to the computer you are running the bot on
