### ISSUE TITLE
the bot is clicking next to the river not center of the mid

### ISSUE THREAD

**Issue by sibrag** [iholston/lol-bot#171]
as the title says how can i fix it?

**Comment by iholston** [comment]
Is your character running into the river?

**Comment by sibrag** [comment]
> Is your character running into the river?

yes

**Comment by iholston** [comment]
I will look into this, in the mean time, try making your minimap a smaller size and it should fix this issue.

**Comment by sibrag** [comment]
Alright thanks, also would be extremely nice if you could add aram gamemode too in this because its still like the same thing, if it can click in the middle and just hit minions would be super nice
