### ISSUE TITLE
v2.2.2 error

### ISSUE THREAD

**Issue by damare1** [iholston/lol-bot#176]
Hello.
I just checked and it stopped with an error, so I am reporting it.
![er](https://github.com/iholston/lol-bot/assets/144917228/8e4cded1-e9d1-4ef7-bd12-f9828ef755fa)
log file
[23122023_1402.txt](https://github.com/iholston/lol-bot/files/13759427/23122023_1402.txt)

**Comment by iholston** [comment]
thanks, this looks like a league of legends client issue rather than a bot issue, but please keep posting these as whenever you see them. and merry Christmas!
