### ISSUE TITLE
How do I set the bot to play? Most of the time it stops or troll (feed)

### ISSUE THREAD

**Issue by salim214** [iholston/lol-bot#179]
**Describe the bug**
How do I set the bot to play? Most of the time it stops or Troll (feed)
**Version**
2.2.2

![Uploading 343d363dea5105d68d484b4841a76435.jpg…]()

**Comment by salim214** [comment]
![343d363dea5105d68d484b4841a76435](https://github.com/iholston/lol-bot/assets/38442926/4f25fdbe-8ffa-4c2b-b0a5-cc1106d7c636)

**Comment by iholston** [comment]
It is recommended that you use a ranged champion (set on the config tab). Non ranged champs die much more than ranged champs. Otherwise, it doesn't matter because you are gaining xp for each match and you only playing against bots.
