### ISSUE TITLE
everything worked perfectly but when in game my champion AFK

### ISSUE THREAD

**Issue by waaikanon** [iholston/lol-bot#180]
like i said everything worked perfectly but when in game my champion AFK
my mouse is plug
sometimes cursor is moving but not click

when in lobby everything fine only problem in game

**Comment by iholston** [comment]
What version are you using?

**Comment by waaikanon** [comment]
lastest version 2.2.2

**Comment by Egon333** [comment]
Same problem

**Comment by bymohamed** [comment]
i have a fix, if you running it using python , create a file start.bat in the same folder as main.pyw and then paste this code : 
start.bat
`@setlocal enableextensions
@cd /d "%~dp0"
py main.pyw
pause`

run this file start.bat as administrator,
if you are using the exe just run it as administrator.

**Comment by iholston** [comment]
@waaikanon does anything here solve your issue
