### ISSUE TITLE
I have bug in riot client 

### ISSUE THREAD

**Issue by joe5050** [iholston/lol-bot#183]
Sometimes riot client bug and refuse to load after the game is done 
So I'm wondering if I can make the bot click on (Restart UX)after every game

**Comment by iholston** [comment]
It is not currently possible to do that. But even though it may look like the client is bugged after a game, it many times is still running like normal. if it is not, the bot should restart the client anyway.

**Comment by joe5050** [comment]
My client stop working and the bot didn't restart ux  every time

Can I add something to the  settings to make it keep restarting the ux no
matter what

**Comment by iholston** [comment]
Unfortunately, there is no way to make the UI restart after every game. Try reinstalling League of Legends perhaps.
