### ISSUE TITLE
the system cannot find the specified file

### ISSUE THREAD

**Issue by lolboter** [iholston/lol-bot#186]
*
![image](https://github.com/iholston/lol-bot/assets/146392091/1138ae5e-e694-48ad-86cb-88811e4875a2)
this is basically what happens to me when i try to launch it 
![image](https://github.com/iholston/lol-bot/assets/146392091/ce0e01da-e189-41c6-b36f-b78777fb72ec)
 and this is the configuration tab
 pls help

**Comment by iholston** [comment]
remove the 'Game' part of the path. 

F:\Lol\League of Legends 

should work.

**Comment by lolboter** [comment]
When i put that path it wont even lunch the bot bcs it says it cannot find path

**Comment by iholston** [comment]
is there a file named LeagueClient.exe in that folder?

**Comment by lolboter** [comment]
There is

**Comment by iholston** [comment]
in the F:\Lol\League of Legends folder or the F:\Lol\League of Legends\Game folder? LeagueClient.exe is usually installed in the "League of Legends" folder not the "League of Legends\Game" folder. there is a separate exe in the Game folder called League of Legends.exe and that is not the correct file.

**Comment by lolboter** [comment]
I was reffering to the leagueclient.exe wich is installed and i checked now in F:\Lol\League of Legends and when i out that path the bot wont load it says it cant find path

**Comment by iholston** [comment]
Try using forward slashes instead of backslashes. Otherwise, im not really sure why it won't run. If it can find F:\Lol\League of Legends\Game, then it should be able to find F:\Lol\League of Legends

**Comment by lolboter** [comment]
Does it maybe have something to do with the fact that i only downloaded python without the addons(things installed with -pip)

**Comment by iholston** [comment]
are you running the .exe? if so you don't need python. if you were running it with python the app would not work unless you installed the -pip requirements. If it is still not working i would reinstall League of Legends and try adding the path the the League of Legends directory to the bot.

**Comment by lolboter** [comment]
I was running the exe but i will put it into the directory and try it

**Comment by iholston** [comment]
no you don't need to put the exe in the directory of League of Legends. Just reinstall league and try adding the path on the config tab like you were doing before.

**Comment by iholston** [comment]
lol glad you got it to work
