### ISSUE TITLE
Increased waiting time for matchups since patch 14.1

### ISSUE THREAD

**Issue by damare1** [iholston/lol-bot#189]
Hi
Rarely, but since patch 14.1, I have noticed longer wait times for matching.
Typically, waiting time is less than 30 seconds., but on rare occasions the wait time can be 10 minutes or more.
Restarting the client will fix this bug.
Conditions for occurrence are unknown.
Version is v2.2.2

**Comment by iholston** [comment]
Yea, I was looking into a fix for this. Been very busy recently, but should be out at some point.
