### ISSUE TITLE
Aram

### ISSUE THREAD

**Issue by warreR33** [iholston/lol-bot#198]
Hello, I was trying to make it work in aram.
I could change the id_lobby. But the bot is trying to select champs in the list.
Any way to make to not selec champs?
Or make it for ARAM mode?

**Comment by warreR33** [comment]
PD: The bot work perfect, just want to know if is possible to play aram with it

**Comment by iholston** [comment]
No, sorry, the bot is only designed for bots. Playing aram is too likely to get the account banned.
