### ISSUE TITLE
The bot stops with an error 24 hours after it starts.

### ISSUE THREAD

**Issue by damare1** [iholston/lol-bot#201]
**Describe the bug**
Recently (about a month ago?) the BOT has been stopping on rare occasions. While trying to find the cause, we noticed that 24 hours after starting the BOT, an error occurs on the next match and the BOT stops.
The screenshot shows the error at the next matching 24 hours after starting the BOT at around 12:20 pm the day before.
The workaround is to restart the client before 24 hours have elapsed.
Is there a solution to this problem?

**Version**
2.2.2

**Screenshots**
![proses](https://github.com/iholston/lol-bot/assets/144917228/07ac5616-8a93-40a3-bede-0133b7f8ff25)

**Log Files**
[07032024_1223.txt](https://github.com/iholston/lol-bot/files/14533016/07032024_1223.txt)

**Comment by iholston** [comment]
hmm my initial thought is that league isnt closing properly, il look into it this weekend.

**Comment by iholston** [comment]
This should be fixed with the latest release v2.3.0 as the bot should be able to close league even when league is frozen.
