### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by Hovados** [iholston/lol-bot#202]
Every time I try to run this program it just shows this. Everything was working fine until yesterday.
![Unhandled exception in script](https://github.com/iholston/lol-bot/assets/153433392/1bf68e6b-218a-4763-bd5f-5ebf4962f987)

**Comment by iholston** [comment]
Looks like your bot is having trouble connecting to the internet maybe?

**Comment by iholston** [comment]
It is trying to get the latest version of the bot from this url:

https://api.github.com/repos/iholston/lol-bot/releases/latest

and it looks like it should be able to get it if you have no internet issues
