### ISSUE TITLE
Banned after 2 games.

### ISSUE THREAD

**Issue by Dano042** [iholston/lol-bot#204]
Hi Im getting banned on all my accounts after letting the bot run for about 2 games. Any solutions for this ?

**Comment by iholston** [comment]
You could be hardware banned. No way to tell unfortunately.

**Comment by Dano042** [comment]
What do you mean by that? 

> You could be hardware banned. No way to tell unfortunately.

What do you mean by that?

**Comment by iholston** [comment]
It means riot may automatically flag any accounts you make and/or level up on that computer so that they will be banned

**Comment by Dano042** [comment]
> It means riot may automatically flag any accounts you make and/or level up on that computer so that they will be banned

oh man thats sad and do you have discord or something like that ?

**Comment by Dano042** [comment]
> It means riot may automatically flag any accounts you make and/or level up on that computer so that they will be banned

I tried to change all my HWIDs and it might just actually work now :O
