### ISSUE TITLE
Patch 14.6.1 implements a new AI mode and BOTs will not work.

### ISSUE THREAD

**Issue by damare1** [iholston/lol-bot#205]
**Describe the bug**
A new AI mode was implemented in patch14.6.1.
Please update the BOT.

**Version**
2.2.2

**Screenshots**
![ai](https://github.com/iholston/lol-bot/assets/144917228/eba62082-b9be-4fbd-9900-fa6d17bdf01e)

**Comment by iholston** [comment]
Interesting, I'll take a look.

**Comment by iholston** [comment]
So I'm not able to recreate this issue. Maybe try restarting the bot and league and see if it is still happening?

**Comment by damare1** [comment]
The problem still occurs. I play on the Japan server.
Is the patch applied to 14.6.1?
A new AI mode has been implemented and the BOT does not work.
![aaaada](https://github.com/iholston/lol-bot/assets/144917228/24aa340b-ba25-4cdd-8979-3fb7a0d56513)

**Comment by iholston** [comment]
Hmm, yea that isn't here in the US yet. If you have time go to the HTTP tab while you are in the intro lobby and paste:

/lol-lobby/v2/lobby

into the URL with the GET method and hit 'Send Request' and copy and past the response here.

**Comment by damare1** [comment]
I am playing on the Japan server. Patch 14.6.1.
A new AI mode has been implemented and seems to have changed the behavior.
I found a solution, though it is a stopgap measure.
If you start the BOT with an AI battle room created in advance, it works.
![su](https://github.com/iholston/lol-bot/assets/144917228/a6d81170-70d4-4309-af15-74c14c66b2fc)
However, if I try to start the BOT from the home screen, it loops from [Creating lobby with lobby_id] and does not seem to work.
![ba](https://github.com/iholston/lol-bot/assets/144917228/f67a29c2-4c2c-43e6-a0f7-0c8a05d6e570)

**Comment by iholston** [comment]
Yea, I think they may have changed the lobby ID. Until that new system is rolled out here in the US I won't be able to update. But I'll check back regularly to see if we get this change. In the meantime, if you have time to send the '/lol-lobby/v2/lobby' in the URL section of the HTTP tab and send response I can see if they changed the lobby id.

**Comment by damare1** [comment]
![rrraaa](https://github.com/iholston/lol-bot/assets/144917228/42b66b29-f485-4717-bf46-d38a148e9050)
error!

**Comment by damare1** [comment]
It seems to be normal when done with an AI room created.
![q1](https://github.com/iholston/lol-bot/assets/144917228/a3e00a0d-82dd-407d-ac65-70f814fcb303)
However, if I do it on the home screen (with the room closed), error message.
![q2](https://github.com/iholston/lol-bot/assets/144917228/b4bc0965-de70-4250-9ac0-b56c7e4f5e78)

**Comment by iholston** [comment]
Can you paste the text from the first one? when the lobby was already created?

**Comment by damare1** [comment]
{
    "canStartActivity": true,
    "gameConfig": {
        "allowablePremadeSizes": [
            1,
            2,
            3,
            4,
            5
        ],
        "customLobbyName": "Custom Lobby",
        "customMutatorName": "",
        "customRewardsDisabledReasons": [],
        "customSpectatorPolicy": "NotAllowed",
        "customSpectators": [],
        "customTeam100": [],
        "customTeam200": [],
        "gameMode": "CLASSIC",
        "isCustom": false,
        "isLobbyFull": false,
        "isTeamBuilderManaged": false,
        "mapId": 11,
        "maxHumanPlayers": 0,
        "maxLobbySize": 5,
        "maxTeamSize": 5,
        "pickType": "",
        "premadeSizeAllowed": true,
        "queueId": 870,
        "shouldForceScarcePositionSelection": false,
        "showPositionSelector": false,
        "showQuickPlaySlotSelection": false
    },
    "invitations": [
        {
            "invitationId": "",
            "invitationType": "invalid",
            "state": "Accepted",
            "timestamp": "0",
            "toSummonerId": 3455471937422816,
            "toSummonerName": ""
        }
    ],
    "localMember": {
        "allowedChangeActivity": true,
        "allowedInviteOthers": true,
        "allowedKickOthers": true,
        "allowedStartActivity": true,
        "allowedToggleInvite": true,
        "autoFillEligible": false,
        "autoFillProtectedForPromos": false,
        "autoFillProtectedForSoloing": false,
        "autoFillProtectedForStreaking": false,
        "botChampionId": 0,
        "botDifficulty": "NONE",
        "botId": "",
        "firstPositionPreference": "",
        "intraSubteamPosition": null,
        "isBot": false,
        "isLeader": true,
        "isSpectator": false,
        "playerSlots": [],
        "puuid": "5e4fb719-a6d5-5b1f-8124-803c93852537",
        "quickplayPlayerState": null,
        "ready": true,
        "secondPositionPreference": "",
        "showGhostedBanner": false,
        "subteamIndex": null,
        "summonerIconId": 29,
        "summonerId": 3455471937422816,
        "summonerInternalName": "",
        "summonerLevel": 5,
        "summonerName": "",
        "teamId": 0,
        "tftNPEQueueBypass": null
    },
    "members": [
        {
            "allowedChangeActivity": true,
            "allowedInviteOthers": true,
            "allowedKickOthers": true,
            "allowedStartActivity": true,
            "allowedToggleInvite": true,
            "autoFillEligible": false,
            "autoFillProtectedForPromos": false,
            "autoFillProtectedForSoloing": false,
            "autoFillProtectedForStreaking": false,
            "botChampionId": 0,
            "botDifficulty": "NONE",
            "botId": "",
            "firstPositionPreference": "",
            "intraSubteamPosition": null,
            "isBot": false,
            "isLeader": true,
            "isSpectator": false,
            "playerSlots": [],
            "puuid": "5e4fb719-a6d5-5b1f-8124-803c93852537",
            "quickplayPlayerState": null,
            "ready": true,
            "secondPositionPreference": "",
            "showGhostedBanner": false,
            "subteamIndex": null,
            "summonerIconId": 29,
            "summonerId": 3455471937422816,
            "summonerInternalName": "",
            "summonerLevel": 5,
            "summonerName": "",
            "teamId": 0,
            "tftNPEQueueBypass": null
        }
    ],
    "mucJwtDto": {
        "channelClaim": "7d880319-5261-4896-acb3-96e09599c341",
        "domain": "lol-pre-game",
        "jwt": "eyJraWQiOiIxIiwiYWxnIjoiUlMyNTYifQ.eyJ0Z3QiOiJqcDEiLCJzdWIiOiI1ZTRmYjcxOS1hNmQ1LTViMWYtODEyNC04MDNjOTM4NTI1MzciLCJpc3MiOiJsb2wtcGFydGllcyIsImNobiI6IjdkODgwMzE5LTUyNjEtNDg5Ni1hY2IzLTk2ZTA5NTk5YzM0MSIsInR5cCI6ImxvbC1wcmUtZ2FtZSIsImV4cCI6MTcxMDkwMzEwNywiaWF0IjoxNzEwOTAyNTA3LCJqdGkiOiI2ODhiYWE4OS03YjkxLTRlOTktOTkwOC1jZTJiYmVhZWY2OGEifQ.h4ceC8EuVf2D-C0h894nqYgb_B5N0JLe4vL1iNiZdEK4E6xx7BbbdMFSC02N_OlXLsqgzpXZQuKKOnqxj51f3ZB7fu0T3xKan9I1JwEs7pKaK_bMZEgSIpsiHd7cAMoIiNhnAC741qhj6KycMuS-2dOO4NtAOO6t9BDVxlspXUslkjGg_y93QzrivlFJwvhp6rJLpZZ1yDbb5TdhrHovmStVWusX-HZZRY-WHrFfvm6RYQHG2ZfpUzhLmwBllNK574mTp51RtXE7zOuE9-fr1D5jQZjNn0UPUn3K0HpwaUwB3-XFbGLM2CTDvEgpkXWEhXo6LbCMSSnfIq-Wt8ea6g",
        "targetRegion": "jp1"
    },
    "multiUserChatId": "7d880319-5261-4896-acb3-96e09599c341",
    "multiUserChatPassword": "eyJraWQiOiIxIiwiYWxnIjoiUlMyNTYifQ.eyJ0Z3QiOiJqcDEiLCJzdWIiOiI1ZTRmYjcxOS1hNmQ1LTViMWYtODEyNC04MDNjOTM4NTI1MzciLCJpc3MiOiJsb2wtcGFydGllcyIsImNobiI6IjdkODgwMzE5LTUyNjEtNDg5Ni1hY2IzLTk2ZTA5NTk5YzM0MSIsInR5cCI6ImxvbC1wcmUtZ2FtZSIsImV4cCI6MTcxMDkwMzEwNywiaWF0IjoxNzEwOTAyNTA3LCJqdGkiOiI2ODhiYWE4OS03YjkxLTRlOTktOTkwOC1jZTJiYmVhZWY2OGEifQ.h4ceC8EuVf2D-C0h894nqYgb_B5N0JLe4vL1iNiZdEK4E6xx7BbbdMFSC02N_OlXLsqgzpXZQuKKOnqxj51f3ZB7fu0T3xKan9I1JwEs7pKaK_bMZEgSIpsiHd7cAMoIiNhnAC741qhj6KycMuS-2dOO4NtAOO6t9BDVxlspXUslkjGg_y93QzrivlFJwvhp6rJLpZZ1yDbb5TdhrHovmStVWusX-HZZRY-WHrFfvm6RYQHG2ZfpUzhLmwBllNK574mTp51RtXE7zOuE9-fr1D5jQZjNn0UPUn3K0HpwaUwB3-XFbGLM2CTDvEgpkXWEhXo6LbCMSSnfIq-Wt8ea6g",
    "partyId": "7d880319-5261-4896-acb3-96e09599c341",
    "partyType": "open",
    "restrictions": [],
    "scarcePositions": [],
    "warnings": []
}

**Comment by iholston** [comment]
Ahh yea, there is the issue. They changed the lobby ID's. Currently, the bot lobbies are 830, 840, and 850. But it looks like the new lobby numbers are probably 860, 870, 880, and/or 890. That should be easy to fix once the update comes out here. I'll keep you updated.

**Comment by damare1** [comment]
Yes, it is. 
The old AI mode and the new AI mode seem to be separate.
Past AI results were also reset.

**Comment by damare1** [comment]
Yes, it is. 
The old AI mode and the new AI mode seem to be separate.
Past AI results were also reset.
![new](https://github.com/iholston/lol-bot/assets/144917228/d6856f67-9335-40fc-8977-1e0b8ec661d3)

**Comment by damare1** [comment]
Understood. Thank you very much.
It has nothing to do with BOTs....
With the new AI update, even INTRO BOTs are getting stronger, so if your team is all BOTs, you are more likely to lose and leveling may be a little slower!

**Comment by LSTMPD** [comment]
EUW here, can confirm everything stated above, 870 (Intro) is the way to go, the bots are much stronger. 
<img width="483" alt="image" src="https://github.com/iholston/lol-bot/assets/34167751/cef54611-c9d4-4bb8-9390-22ed4e7a17a0">
Did 2 games in order to try it out, pretty surprised at how fast the enemy snowballs now. 
Also probably worth mentioning, seems like Riot disabled Autobuy when leaving the fountain on Intro difficulty.

**Comment by damare1** [comment]
Thanks for the info.
I did a little intermediate, but I'm going back to introductory.

**Comment by bjohni** [comment]
is it possible the bot to be fixed?

**Comment by iholston** [comment]
The patch is finally here in the US and I'll have a hotfix out tomorrow.

**Comment by bjohni** [comment]
> The patch is finally here in the US and I'll have a hotfix out tomorrow.

tysm

**Comment by bjohni** [comment]
![21](https://github.com/iholston/lol-bot/assets/164339694/9a8db78f-5d5a-4e3c-8773-265579d3d45a)
its still now working

**Comment by iholston** [comment]
Thats because you are still using the old version. The new version is v2.3.0 and is out now

**Comment by bjohni** [comment]
![123](https://github.com/iholston/lol-bot/assets/164339694/280a532a-e2f3-4d75-a8d0-2f003c815c34)
![1234](https://github.com/iholston/lol-bot/assets/164339694/81d683bc-6bd2-4849-9685-4cc0dc03811b)
idk whats going on:/

**Comment by iholston** [comment]
Yea just change the 'game mode' on the config tab a single time and it should fix that. That is from the previous saved version of the bot.

**Comment by bjohni** [comment]
thanks,its working now.

**Comment by temmo19** [comment]
hello,i need help please guys,how do i fix this error,
[21:01:10] [INFO   ] Overwriting game configs
[21:01:10] [ERROR  ] [Errno 13] Permission denied: 'C:/Riot Games/League of Legends\\Config/game.cfg'
[21:01:10] [ERROR  ] Traceback (most recent call last):
  File "C:\Users\x\Desktop\lol-bot-2.3.0\lolbot\bot\client.py", line 69, in account_loop
    self.leveling_loop()
  File "C:\Users\x\Desktop\lol-bot-2.3.0\lolbot\bot\client.py", line 103, in leveling_loop
    self.set_game_config()
  File "C:\Users\x\Desktop\lol-bot-2.3.0\lolbot\bot\client.py", line 389, in set_game_config
    shutil.copy(utils.resource_path(Constants.GAME_CFG), path)
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 419, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:/Riot Games/League of Legends\\Config/game.cfg'

[21:01:10] [ERROR  ] Unknown Error. Exiting

**Comment by iholston** [comment]
@temmo19 this issue is not related to the current thread. There are two other threads with this same issue. You may just have to delete the file.

**Comment by temmo19** [comment]
> @temmo19 this issue is not related to the current thread. There are two other threads with this same issue. You may just have to delete the file.

im not gonna like i did delete it more than 3 times at least,uninstalled it and installed again,its first time im having a problem with the program,ive been using it since long time now i have no idea how to fix it

**Comment by iholston** [comment]
Make sure the read only flag is not checked under properties. But other than that im not really sure how to fix this particular issue.
