### ISSUE TITLE
v2.3.0 BOT will stop after 24 hours.

### ISSUE THREAD

**Issue by damare1** [iholston/lol-bot#213]
**Describe the bug**
A new version is released, but still the bot stops after 24 hours.
[An unknown error has occurred]. message appears and the client is forced to terminate.

**Version**
2.3.0

**Screenshots**
![ya](https://github.com/iholston/lol-bot/assets/144917228/9f96bec8-9426-4d04-8179-91e23490378c)

**Log Files**
[logfile.txt](https://github.com/iholston/lol-bot/files/14782970/logfile.txt)

**Comment by iholston** [comment]
Does the bot not auto restart the client?

**Comment by damare1** [comment]
![w1](https://github.com/iholston/lol-bot/assets/144917228/bf4deca5-b9e8-44d1-afe0-966a674bb96d)
[log.txt](https://github.com/iholston/lol-bot/files/14812022/log.txt)
After the error message, the client is killed and the BOT is stopped. It will not restart.
What could be the cause?

**Comment by ZaryImortal** [comment]
Did you open the program as Administrator?

**Comment by damare1** [comment]
No

**Comment by damare1** [comment]
If I leave RiotClient running, it restarts. However, an error message like the one in the image appears.
![Uploading errr2.PNG…]()

**Comment by damare1** [comment]
If I leave RiotClient running, it restarts. However, an error message like the one in the image appears.
![errr2](https://github.com/iholston/lol-bot/assets/144917228/f0406438-9236-4440-a7f6-de7e01716deb)
