### ISSUE TITLE
a error 

### ISSUE THREAD

**Issue by wangxin2112** [iholston/lol-bot#214]
**Describe the bug**

**Version**
What version of the lol-bot are you running?

**Screenshots**

**Log Files**
If applicable, add the log file containing the error messages from your issue

**Additional context**

**Comment by wangxin2112** [comment]
![image](https://github.com/iholston/lol-bot/assets/66788722/4b78a417-a118-43d7-a90c-bca28d5815e9)
how to solve ,THX

**Comment by iholston** [comment]
This should be fixed in the latest release.
