### ISSUE TITLE
Boy stays in jungle doesn’t go mid

### ISSUE THREAD

**Issue by Seedvacker** [iholston/lol-bot#216]
Bot clicks mini map and stays in jungle how do I fix

**Comment by Seedvacker** [comment]
I don’t understand the bot loads the game up then just makes the champion stay in jungle what’s going on?

**Comment by iholston** [comment]
If you have been changing the minimap size or not allowing the bot to override the config file then it won't be able to go mid. I would simply try making the minimap smaller. I don't remember the exact size the minimap is supposed to be.
