### ISSUE TITLE
change onother champs

### ISSUE THREAD

**Issue by chris7-dell** [iholston/lol-bot#224]
**Describe the solution you'd like**
how to change onother champs is very dangerous feed only with 1 champ
**Version**
v2.3.0

**Additional context**
![image](https://github.com/iholston/lol-bot/assets/52637874/645a7d05-9370-417b-b834-3534676e71f0)

**Comment by iholston** [comment]
You can change the champs in the settings. But it depends on what champs you own on the account and what champs the other players pick.

**Comment by iholston** [comment]
This should be fixed in the latest release. Champions will be randomly selected based on all available champs in the account.
