### ISSUE TITLE
Bot doesnt auto start a new game after game is completed.

### ISSUE THREAD

**Issue by roarnoob** [iholston/lol-bot#227]
![image](https://github.com/iholston/lol-bot/assets/39672046/317455f8-c325-4791-a1cf-ed4a0202aacb)

Hello brother , was trying out your bot , it used to work fine for like 1-3 months . However recently,  after a game ended the lol bot will crash at the page asking people to honor the players. Any idea what is the reason ? Thanks!!

**Comment by tuilaxibui** [comment]
Me too

**Comment by roarnoob** [comment]
anyway i found a way to fix it on my own .... i wrote a script to click the start bot button when league of legends in game client closes . so its a band aid fix

**Comment by tuilaxibui** [comment]
How ??? help me.

**Comment by tuilaxibui** [comment]
Can you give me that script ?? Please.

**Comment by iholston** [comment]
I should be able to get a fix out sometime soon. It's been a very busy summer for me.

**Comment by tuilaxibui** [comment]
> I should be able to get a fix out sometime soon. It's been a very busy summer for me.

When you can do :'(:'(. I just buy ticket.

**Comment by petetee59** [comment]
roarnoob can you help us please give me script

**Comment by Damascenoga** [comment]
Are you able to level up the account without getting permanently banned? If so, how? I've already lost 3 accounts...

**Comment by unobatbayar** [comment]
You can solve this problem by not honoring anyone. I guess there is problem with the API.

```python
    def honor_player(self) -> None:
        self.connection.request('post', '/lol-honor-v2/v1/honor-player', data={"summonerId": 0})  # will clear honor screen
        return
```

This way, it doesn't break the loop.

**Comment by iholston** [comment]
Should be fixed with the latest release
