### ISSUE TITLE
New Beta Bots caused the program to not work

### ISSUE THREAD

**Issue by hubman-star** [iholston/lol-bot#228]
**Describe the bug**
New Beta Bots caused the program to not work for Introbots

**Version**
2.3.0

**Screenshots**
![image](https://github.com/iholston/lol-bot/assets/60443304/6a800635-91f1-4fe5-a131-cf4f8c64f081)

**Log Files**
[a.txt](https://github.com/user-attachments/files/16034013/a.txt)

**Additional context**
**None.**

**Comment by hubman-star** [comment]
I managed to fix it :D

**Comment by Damascenoga** [comment]
Are you able to level up the account without getting permanently banned? If so, how? I've already lost 3 accounts...

**Comment by hubman-star** [comment]
Currently its unable to honor, as it spits an error.

**Comment by iholston** [comment]
this should be fixed in the latest release
