### ISSUE TITLE
[INFO   ] League Installation Path is Invalid. Update Path

### ISSUE THREAD

**Issue by registro1154** [iholston/lol-bot#238]
**Describe the bug**
[INFO   ] League Installation Path is Invalid. Update Path

**Version**
v2.3.0

**Screenshots**
![Screenshot_8](https://github.com/user-attachments/assets/714e77d9-b7a6-4164-98f5-a58d191958c5)

**Log Files**
![Screenshot_8](https://github.com/user-attachments/assets/9e45bacf-8a97-44d2-831e-71bb52d0e4f9)

**Additional context**
I already put it in accounts, which is my current account, and I have python downloaded

**Comment by iholston** [comment]
You need to go to the config tab and add the location of your league of legends installation
