### ISSUE TITLE
I GOT BANNED AND HARD RESET AND I GOT BANNED 1 LVL ?

### ISSUE THREAD

**Issue by fakiramazengin** [iholston/lol-bot#240]
I got banned. I returned my computer to factory settings and did a hard reset. Then I got banned while downloading league again. Even though I reset the computer, I get banned. How should I clean it? What should I do?

**Comment by iholston** [comment]
You are probably hardware banned. I would look into spoofing your mac address. Additionally, in the future, run the bot in MacOS or use python instead of the .exe.
