### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by unobatbayar** [iholston/lol-bot#242]
**Describe the solution you'd like**
Since it's created using python is it possible to also support macOS?

**Version**
v2.3.0

**Additional context**

I'm currently trying but if you have any tips, please let me know.

**Comment by unobatbayar** [comment]
I might just install Windows using Boot Camp.

**Comment by iholston** [comment]
I would recommend running it via python on MacOS. The bot is currently under fire from vanguard and riot bans. Vanguard is not available on MacOS so you are far less likely to get banned.

**Comment by unobatbayar** [comment]
Thank you for creating this. That's a good point to consider.

**Comment by unobatbayar** [comment]
I have one question, how did you make the LolBot.exe? Did you use Pyinstaller?
