### ISSUE TITLE
How to run it with pyton

### ISSUE THREAD

**Issue by Faker1327** [iholston/lol-bot#249]
**Describe the solution you'd like**
It does not give skills and how to get different heroes?
**Version**
What version of the lol-bot are you running?
2.3.1
**Additional context**
It only takes Tristana and does not add any skills. I can provide these randomly. Also, how to run it from Python. There is launcher.bat in the video on the home page, it is not in the file I downloaded.

not:I installed Python but I can open it from exe. How can I open it from Python?

**Comment by Faker1327** [comment]
He doesn't use hero abilities in the trick, he just makes straight hits.

**Comment by iholston** [comment]
You should look at how to install and run python programs. There are many tutorials on youtube.
