### ISSUE TITLE
2.3.1 No Ban?

### ISSUE THREAD

**Issue by damare1** [iholston/lol-bot#254]
I haven't seen it in a while and it was updated to 2.3.1.
If I don't run the .exe and run it in Python, can I avoid the BAN?
I don't have a Mac.

**Comment by iholston** [comment]
That's what I do. And I haven't seen any accounts get banned.

**Comment by damare1** [comment]
OK.
I'll try it in python.

**Comment by damare1** [comment]
Is it the [Source Code (zip)] one that you are downloading?
I have downloaded this before and got banned.(2.3.0)
I am really worried that I will be banned.
I do not want to have a HWID BAN imposed.

**Comment by iholston** [comment]
Your best bet is to wait until the bot is ported to macOS and run it there. I would not recommend running this particular bot on Windows.
