### ISSUE TITLE
AttributeError click

### ISSUE THREAD

**Issue by intelligencemouse** [iholston/lol-bot#256]
after the match i am getting this error it does not stay in loop how can i solve this

[ERROR  ] module 'lolbot.common.proc' has no attribute 'click'
[ERROR  ] Traceback (most recent call last):
  File "lolbot\bot\bot.py", line 66, in run
  File "lolbot\bot\bot.py", line 111, in leveling_loop
  File "lolbot\bot\bot.py", line 245, in pre_end_of_game
AttributeError: module 'lolbot.common.proc' has no attribute 'click'

 [ERROR  ] Unknown Error. Exiting

**Comment by iholston** [comment]
Yep, this is a bug and should be fixed by the end of the week.
