### ISSUE TITLE
I can't run it on macOS Sonoma 

### ISSUE THREAD

**Issue by RigobertoEHA1** [iholston/lol-bot#257]
I try. to run the bot on macOS but dependencies like pywin32 can't install, ctypes.windll trouble, and more, can u give a guide or run it on macOS, please, im try but doesn't works

**Comment by iholston** [comment]
macOS support is not here yet. It will be out in the next week or two. Until then it can't be run on mac unless you fork it and fix the issues manually.

**Comment by Jimz71** [comment]
Anyway vanguard on mac is planned for the end of 2024

**Comment by iholston** [comment]
Vanguard is not coming to mac according to https://www.leagueoflegends.com/en-us/news/dev/dev-vanguard-x-lol-retrospective/ . They are basically just calling packman (the og anti-cheat) vanguard 2, its completely harmless.

**Comment by iholston** [comment]
@RigobertoEHA1 the bot should run on MacOS in the latest release v4.0.0+

**Comment by Jimz71** [comment]
Yeah, just checked you're right. No kernel access = no memory inspection. It's going to be a mess for them to detect Python stuff, as macOS is much better protected than Windows.

Riot also likes to sue cheat/bot platforms when they have no other options.

**Comment by Jimz71** [comment]
> macOS support is not here yet. It will be out in the next week or two. Until then it can't be run on mac unless you fork it and fix the issues manually.

Yeah, just checked you're right. No kernel access = no memory inspection. It's going to be a mess for them to detect Python stuff, as macOS is much better protected than Windows.

Riot also likes to sue cheat/bot platforms when they have no other options.

**Comment by Jimz71** [comment]
> Vanguard is not coming to mac according to https://www.leagueoflegends.com/en-us/news/dev/dev-vanguard-x-lol-retrospective/ . They are basically just calling packman (the og anti-cheat) vanguard 2, its completely harmless.

Yeah, just checked you're right. No kernel access = no memory inspection. It's going to be a mess for them to detect Python stuff, as macOS is much better protected than Windows.

Riot also likes to sue cheat/bot platforms when they have no other options.
