### ISSUE TITLE
League Game going to right bottom corner

### ISSUE THREAD

**Issue by wgtrr** [iholston/lol-bot#267]
Hey so whenever im running the bot and it picks champion and it goes into loading screen the game goes to right bottom corner and the error i get is PyAutoGUI fail-safe triggered from mouse moving to a corner and then after some times the game closes and never re opens (im not touching my mouse at all i even have it unplugged and it still does it)

**Comment by wgtrr** [comment]
it seems like i found a fix to it i just had my output from pc displayed on my tv and it has lower resolution than 1920x1080 which resulted in that problem but now that i tried different display it works flawlessly  atleast for now

**Comment by wgtrr** [comment]
it happens on 1920x1080 aswell so idk

**Comment by iholston** [comment]
hmm okay, il look into this. Thanks

**Comment by iholston** [comment]
is this still an issue on the latest version?

**Comment by wgtrr** [comment]
> is this still an issue on the latest version?

idk i got perma banned and gave up on leveling

**Comment by iholston** [comment]
Sorry for your loss brother
