### ISSUE TITLE
Bot does things out of order and can easily be spotted as a bot

### ISSUE THREAD

**Issue by TimeToFixStuff** [iholston/lol-bot#278]
**Describe the bug**
I created a new account, because the bot just isn't acting the slightest bit human. It goes to mid, opens the store and tries to buy something, then recalls and fails to buy something again. It attacks only minions and CONSTANTLY goes back to the turret. Many times it runs from the store to the outer area and then recalls to buy more stuff. The enemies kill the bot constantly and ranged chaps like Smolder can kill the bot when it retreats to a turret and stands there trying to recall. It kind of looks like the player is intentionally feeding. Even when that turret is destroyed, the bot acts as if it were still there. When the bot gets to "Waiting for Minion Clash", it never advances past that in the log window until the game is over.

**Version**
What version of the lol-bot are you running?
Latest version of the bot and LoL.

**Additional context**
I'm on a MacBook Pro M3 Pro with 32GB ram.

**Comment by iholston** [comment]
Yea, the bot is not designed to play like a human. It should successfully buy items though, and the logs should be updated to reflect the state of the bot more accurately now in the latest release. Riot is not running advanced heuristics in bot lobbies to determine if players are bots or not. If you would like to, open a new issue about the bot not purchasing items with some more detailed information!
