### ISSUE TITLE
more a request than a isssue

### ISSUE THREAD

**Issue by Wdohipe** [iholston/lol-bot#28]
Hi, I'm testing a lot of your code as my playground(I'm new to python). Could you add a feature that would set the game window to the top left corner (0, 0 pixel) or tell me how to do it? (I tried but it didn't work)

**Comment by iholston** [comment]
Glad you are enjoying the code. I don't honestly know the best way to achieve this off the top of my head. There may be a setting in the game.cfg file that will automatically open the window somewhere (you would have to look online at all the possible settings for this file), other than that you could try and use pyautogui to get the game window and move it where you want it, but I know that pyautogui window stuff is pretty unreliable sometimes.

Other than that you could just change the game.cfg to make the window fullscreen or fullscreen borderless and perhaps that will accomplish a similar effect to what you want.
