### ISSUE TITLE
connection error on vm

### ISSUE THREAD

**Issue by kaorumitoma** [iholston/lol-bot#29]
try to use vm to run the bot but can't connect to game(i know this is not a new issue but i can't a way to solve it so i post it again)
![10061](https://github.com/iholston/lol-bot/assets/134698373/55036dcf-4ca6-4cc6-b2c5-a519c062eccd)
about log file,i can't find the log.txt file on my desktop(vm)

**Comment by iholston** [comment]
Yea I haven't been able to look into vm issues yet. And the log file will now sometimes not get created if the desktop path doesn't work.

**Comment by kaorumitoma** [comment]
fixed.

**Comment by iholston** [comment]
You say its fixed, what was the solution?

**Comment by iholston** [comment]
Sweet, thanks!
