### ISSUE TITLE
Transition error. Phase will not change.

### ISSUE THREAD

**Issue by kaorumitoma** [iholston/lol-bot#31]
[logs.txt](https://github.com/iholston/lol-bot/files/11901986/logs.txt)
As title.
here is the log file.Thank you!

**Comment by iholston** [comment]
Has this issue still been popping up for you?

**Comment by kaorumitoma** [comment]
Recently no.

**Comment by iholston** [comment]
okay, was probably a one time thing cuz i havent really seen this issue or been able to properly recreate it.
