### ISSUE TITLE
Doesn't move

### ISSUE THREAD

**Issue by alperkyoruk** [iholston/lol-bot#33]
everything is normal at first. the bot gets in the game, buy the item but cannot move to mid. It just doesn't click mid. any idea how to solve this?

**Comment by iholston** [comment]
If it buys items then I think that makes it fundamentally different than issue #7. After buying items does the bot leave the fountain?

**Comment by alperkyoruk** [comment]
yes, It doesn't leave the fountain. It presses heal in the begining, brings cursor to map but cannot click right to move there

**Comment by iholston** [comment]
Is it actually purchasing items? If it's able to purchase items im not sure why it would not be able to click on the mini map..

**Comment by iholston** [comment]
Any update on this? is this still a recurring problem? I'm not sure there is anything I can do from a code perspective to fix this issue.
