### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by ThickPigeon** [iholston/lol-bot#35]
when i launch the bot it shows PermissionError: [Errno 13] Permission denied , and it just doesnt work can some1 please help? i would rlly appreciate it

**Comment by ThickPigeon** [comment]
[14072023_2250_log.log](https://github.com/iholston/lol-bot/files/12053837/14072023_2250_log.log)
this is the log

**Comment by ThickPigeon** [comment]
i fixed it

**Comment by iholston** [comment]
What was the solution?
