### ISSUE TITLE
ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### ISSUE THREAD

**Issue by kaorumitoma** [iholston/lol-bot#37]
the bot play two games and show this error message.
heres the log.please help.
[20072023_1848_log.log](https://github.com/iholston/lol-bot/files/12106197/20072023_1848_log.log)

**Comment by kaorumitoma** [comment]
yes

**Comment by marciomvm** [comment]
What we should do to make that run on a vm?

**Comment by iholston** [comment]
Currently, I will not be able to fix VM related issues. If you figure out a solution please let me know.
