### ISSUE TITLE
Can I ask how to edit this script to make it queue in intro bots instead? 

### ISSUE THREAD

**Issue by mish20011** [iholston/lol-bot#38]
Nobody is queuing in that difficulty, its mostly intro and intermediate. With intro full of bots like this also and intermediate being real people.

I have zero knowledge in coding, so maybe sharing me a file with edited script can help a lot, thank you

**Comment by iholston** [comment]
Sure, once you have downloaded the repo, go into the constants.py file on line 32
> GAME_LOBBY_ID = BEGINNER_BOTS_GAME_LOBBY_ID
change it to 
> GAME_LOBBY_ID = 830
and save it. 830 is the lobby id for intro bots (i think, if its not let me know)

**Comment by iholston** [comment]
Sure, once you have downloaded the repo, go into the constants.py file on line 32
> GAME_LOBBY_ID = BEGINNER_BOTS_GAME_LOBBY_ID

change it to 

> GAME_LOBBY_ID = 830

and save it. 830 is the lobby id for intro bots (i think, if its not let me know)

**Comment by mish20011** [comment]
it works now but... the bot looks so dumb. its jist auto running to down at bot tier 3 tower, and keeps spam purchasing chainmail, it doesn't even cs unlike the other bots in the game that I've been with, it felt like the most obvious bot

**Comment by iholston** [comment]
Right because the bot is designed to play in beginner or intermediate bots. It wouldn't be hard to tweak the bot to play  in intro bots but as you haven't any programming knowledge you may want to just play in beginner or intermediate bots.
