### ISSUE TITLE
Can't make it work:(

### ISSUE THREAD

**Issue by NikolaiChalakov** [iholston/lol-bot#4]
![liga](https://user-images.githubusercontent.com/115649460/235346874-f096723b-56f8-44f8-a338-c792696523be.png)
![liga2](https://user-images.githubusercontent.com/115649460/235346879-c3bd52d5-82a9-4d0a-b3a7-83ef152df4e9.png)
idk what the problem is but even after updating the path ,its not working

**Comment by iholston** [comment]
Try changing the backslashes in the path to forward slashes 'D:/riotgames/Riot Games/League of Legends'

**Comment by NikolaiChalakov** [comment]
It worked thank you very much:D
