### ISSUE TITLE
It dosnt buy anything on shop

### ISSUE THREAD

**Issue by Caua-ferraz** [iholston/lol-bot#49]
Somewhy It dosnt buy anything on my shop

**Comment by iholston** [comment]
The shop needs to be in the default shop position. Try and line up the "purchase" button with where the bot is trying to click in the bottom right. Or there might be a setting to return the shop to default position, but I'm not sure.

**Comment by Gouthar** [comment]
I have a problem with shop too..
When he back to b he try to buy something but dont buy anything.. just bought 1 boot and 1 doran in all the match

**Comment by iholston** [comment]
@Gouthar does the shop open in the default position?

**Comment by Gouthar** [comment]
I did not change the position, is all default

**Comment by iholston** [comment]
I can then only reiterate what I stated in issue #17. 

> The bot can only purchase items if the shop is in the default/original shop position. If the shop has moved, I would try and line up the "Purchase" button. The bot will attempt to click on an item and then click on "Purchase" to actually buy the item. Whenever you see the bot trying to buy something take note of where it thinks the "Purchase" button is and move the shop accordingly.
