### ISSUE TITLE
pyautogui fail-safe triggering

### ISSUE THREAD

**Issue by NikolaiChalakov** [iholston/lol-bot#5]
![problem](https://user-images.githubusercontent.com/115649460/235698761-d431fba4-9b81-4e7e-b386-54c06d9db7a8.png)

**Comment by iholston** [comment]
I think I know the issue, should be able to get a fix out later today.

**Comment by iholston** [comment]
Let me know if you still have the issue, il leave this open for a while. The guaranteed fix is to directly disable the failsafe via 'pyautogui.FAILSAFE = False' but the bot should not run into that issue in the first place.

**Comment by iholston** [comment]
I am going to close this issue, as I assume the fix worked and there should be no more fail-safe activations. If it happens again I can reopen.
