### ISSUE TITLE
How to change gametype to ARAM ?

### ISSUE THREAD

**Issue by marius-toupain** [iholston/lol-bot#54]
Hello,
Thanks for the bot it works perfectly ! I was just wondering if you could share the GAME_LOBBY_ID for ARAM because in the contants.py file, there are already 2 IDs (BEGINNER_BOTS_GAME_LOBBY_ID = 840 and INTERMEDIATE_BOTS_GAME_LOBBY_ID = 850). Since after level 20, the EXP gained is reduced to 65% when you play more than 3h a day, I was thinking about switching the game mode from COOP vs AI to ARAM afte level 20. 

- First, do you have such an ID ? I didn't find the 840 and 850 so maybe you could know this one. 
- Also, is it safe to use this tool in ARAM (because it is PVP and not vs AI games)

Thanks for your work !

**Comment by marius-toupain** [comment]
Actually, I just tried some values. I found out that : 

- RANKED_SOLO_DUO_GAME_LOBBY_ID = 420
- NORMAL_BLIND_GAME_LOBBY_ID = 430
- RANKED_FLEX_GAME_LOBBY_ID = 440
- ARAM_GAME_LOBBY_ID = 450

So my last question remains : is it safe to use this tool in ARAM (because it is PVP and not vs AI games) ?

**Comment by iholston** [comment]
This tool is not safe to use in pvp. You will almost always get reported by the real life players. 

Players in ARAM want to win and have a good time. They will get angry when they see the bot and report. Players in beginner or intermediate bots won't get angry and usually won't be able to tell that the mid landers is a bot either. 

So in conclusion, you absolutely can play the bot in ARAM, but your account will be reported non-stop and be banned.

**Comment by marius-toupain** [comment]
Ok thanks for the info !
