### ISSUE TITLE
trouble buying

### ISSUE THREAD

**Issue by T000b4** [iholston/lol-bot#56]
I have a problem, when it enters the game it stays on the purchase screen and the program closes. you have to buy it manually for it to work.

**Comment by iholston** [comment]
have you taken a look at #17 ? the shop needs to be in the default position. otherwise you might need to reposition it based on where it thinks the purchase button is.

**Comment by iholston** [comment]
No, the game will open in 768x1024 and thus the ratio will always work. You just need to line it up.

**Comment by eimendir** [comment]
okay that's odd, maybe my script isn't the latest, It doesn't seem to align with the map unless set to 1920x1080. BTW awesome work on this!
