### ISSUE TITLE
Afk warning

### ISSUE THREAD

**Issue by Kenry26** [iholston/lol-bot#58]
The bot buys random items go mid and standing behind turret and opening shop for second time and then i get afk warning because not moving after few mins bot moves.
Did i mess up something?

**Comment by iholston** [comment]
Can you send a video or screenshot to explain your issue? Is the bot actually getting the afk punishment or just a warning?

**Comment by Kenry26** [comment]
I tried to record on my pc and it works fine, but yesterday on virtual machine had that problem..... Should my screen need to have a resolution to work propertly? but heres a screenshot when it opens shop on 1:28 
![vlcsnap-2023-08-26-12h27m12s402](https://github.com/iholston/lol-bot/assets/71223909/6e8e5785-c09e-455d-9269-7f0ae2776769)

**Comment by iholston** [comment]
oh I did not realize that it was a virtual machine issue. You may just have to tinker with your vm settings. Like I say in the readme, vm issues aren't something that i can diagnose. It is not a problem with the bot, its just a problem with your specific setup. best of luck though!

**Comment by Kenry26** [comment]
Oh in that case thanks for help :D

**Comment by Kenry26** [comment]
Yesterday I got banned on Euw on acc I botted, there are lot of real players on Bot Beginner.
But on Bot Intro there's almost no player. For safety I recommend to use 830 bot intro.

**Comment by sonicwil** [comment]
@Kenry26 Are you currently experiencing bans with vm?
