### ISSUE TITLE
launch bot on multiple vms

### ISSUE THREAD

**Issue by mbelhaouz** [iholston/lol-bot#6]
Hello there,

i m here to report an issue about using the bot on multiple VMs i think it is related to sessions that are created. ( or maybe many bots are asking get request to the same local host server with same port (2999) to get the data is the problem, i'm not sure tho )

![image](https://user-images.githubusercontent.com/48966307/236287485-eac17d38-9b64-453f-8d91-5a6d3c298d8c.png)

**Comment by mbelhaouz** [comment]
![image](https://user-images.githubusercontent.com/48966307/236352798-a0a0d70f-1078-46e1-b01e-e73a7bf61c49.png)

**Comment by iholston** [comment]
How many vms are running successfully and what os are they running?

**Comment by mbelhaouz** [comment]
i created 4 but even while launching one bot on my main pc and one on VM it does not work

**Comment by iholston** [comment]
Right so my main question is about whether league is running properly in the vm. Can you manually play league games in your vm? I believe there currently are ways to get league running properly in a vm but I havent tried them. I know riot cracked down on that a while ago. I run all my bots on hardware that I have access to.

**Comment by mbelhaouz** [comment]
yes it tried launching league on the vm and it was working ( u need to add some specific config to the .vmx file of the vm and it will work, this is the link to do that https://www.unknowncheats.me/forum/league-of-legends/480977-run-league-legends-virtual-machine-vmware.html )

But yea to answer your question it was working, i launched first bot on VM, and it was working well, and then i launched a second VM and than Boom, not working anymore and the screenshots i sent you

**Comment by iholston** [comment]
Hmmm okay, I will try and look into this towards the end of the month, currently working on a similar bot for valorant atm and this issue could be something vmware specific, but I'll let you know!

**Comment by kasperzi** [comment]
How to implement more then one account in accounts.py ?

**Comment by iholston** [comment]
At the moment I do not have to resources to fix VM related issues. If you figure out a solution please let me know. Thanks
