### ISSUE TITLE
Error when game starts

### ISSUE THREAD

**Issue by Luxuriaxd** [iholston/lol-bot#61]
Hello please help me with my problem, when the match started there are some errors and my character is not moving. So I need to restart the cmd to make my character move. 

Here's the screenshot of the error I hope you can help me with this
![Screenshot 2023-08-28 171240](https://github.com/iholston/lol-bot/assets/143393921/cc1c2a65-4036-4369-ab69-b12761dd3e7f)

**Comment by iholston** [comment]
Did you remove the dialogs options from the config.py? If so, this is actually a bug I will mneed to fix.

**Comment by iholston** [comment]
The temporary solution is to put at least one dialog option back..
