### ISSUE TITLE
lobby id for into bots

### ISSUE THREAD

**Issue by KripticEyeGaming** [iholston/lol-bot#62]
hello, im new to python and coding and was wondering how to switch to intro bots. i managed to figure out the intermediate bots lobby ID (850) but just used:
         start_matchmaking(INTERMEDIATE_BOTS_GAME_LOBBY_ID)

though im unable to get it working with:
         start_matchmaking(INTRO_BOTS_GAME_LOBBY_ID)

**Comment by iholston** [comment]
Intro bots lobby id i believe is 830. I am not sure that the bot works correctly in that mode but it might work. In either case, if you want to run it in intro bots, undo your current changes and simply change line 32 in constants.py to 

> GAME_LOBBY_ID = 830

**Comment by KripticEyeGaming** [comment]
yeah, ended up figuring it out, also what are the champion priorities for this script and why do does the script barely use any abilities?

**Comment by iholston** [comment]
Champion priorities come from line 36 in constants.py, you can find a list of champions and their numbers on google pretty easily. It will follow that order then try any free to play champs.. As for abilities, it doesn't use them becuz it is unnecessary as well as difficult to implement.
