### ISSUE TITLE
Login Failure

### ISSUE THREAD

**Issue by sonicwil** [iholston/lol-bot#63]
After accessing the account, the bot is not clicking on "league of legends" to proceed and enter the game, do you know what I can do to fix it?

**Comment by iholston** [comment]
Actually, this is an issue that is currently being worked on. Dealing with the riot client needs improvement. In the meantime, you should only have to click on league of legends one time, after that it should directly open after login.

**Comment by sonicwil** [comment]
Okay, thanks!

**Comment by iholston** [comment]
Gonna leave this as open until its fixed.

**Comment by Daro4231** [comment]
clicking on league of legends dont work for me any other ways?

**Comment by iholston** [comment]
Not quite sure what you mean here @Daro4231, you may have to manually start league of legends via the Riot Client after the bot logs in. But once you do that the bot should be able to run normally because league of legends will start automatically after login from then on...

**Comment by Daro4231** [comment]
I'm doing exactly that I'm opening league from riot client but then bot gets paused

**Comment by iholston** [comment]
go into your logs folder and drop the log from this issue that you are referencing.

**Comment by Daro4231** [comment]
[13 Sep 2023 15:38:01] [INFO   ] [launch_league        ] Overwriting/creating game config
[13 Sep 2023 15:38:01] [INFO   ] [launch_league        ] Retrieving account credentials
[13 Sep 2023 15:38:01] [INFO   ] [launch_league        ] Launching League of Legends
[13 Sep 2023 15:38:12] [INFO   ] [launch_league        ] Riot Client opened. Logging in
[13 Sep 2023 15:38:12] [ERROR  ] [login                ] Failed Authentication Request. Response: 400

**Comment by Daro4231** [comment]
this is just repeating over and over

**Comment by Daro4231** [comment]
then i tried opening league from client after the bot opens the riot client but afterwards the bot pauses and says "press any key to continue" no matter what i press the bot shut downs

**Comment by iholston** [comment]
Are you sure your username and password are correct? Authentication failure usually means bad username or password. Additionally I believe there is a newer version of the bot out now...

**Comment by Daro4231** [comment]
I have keep me signed in checked and I log in perfectly fine and where do I download newer version

**Comment by Daro4231** [comment]
Cause I downloaded yesterday

**Comment by iholston** [comment]
Any update on this @Daro4231 ? Try the newest bot (v1.3.1) and let me know if you still have this issue
