### ISSUE TITLE
Starter items menu not buying/closing

### ISSUE THREAD

**Issue by n-tdi** [iholston/lol-bot#64]
When opening the menu to buy items for the first time when you load into the game, the menu doesn't close and the bot clicks around it but never does anything, this causes me to get afk kicked unless I intervene. Let me know if there is anything I can provide to help debug

**Comment by iholston** [comment]
you running in a vm?

**Comment by n-tdi** [comment]
No. I'm running on windows 11. My monitor is 2660 x 1440

**Comment by iholston** [comment]
This issue might be similar to #7. Does the bot push mid?

**Comment by n-tdi** [comment]
Yes! After i close the shop myself the bot functions perfectly fine

**Comment by iholston** [comment]
Yea, im not sure what could be causing this because the bot opens/closes the shop by sending the keypress 'p' so if it can open the shop it should be able to close it. Something about your setup is causing it to miss one of the 'p' keypresses.

**Comment by n-tdi** [comment]
Is it possible that it could be missing the purchase button? As it clicks on an item, then right above the purchase button, back and forth until afk kicked.

**Comment by iholston** [comment]
you could try moving the shop up a little then. But the shop should close and the bot should just play without any items.

**Comment by n-tdi** [comment]
Alright i'll report back to you with more info.
