### ISSUE TITLE
Starts at 240FPS

### ISSUE THREAD

**Issue by damare1** [iholston/lol-bot#66]
When you start the launcher, it starts at 240FPS. Can you make it 25FPS?

**Comment by iholston** [comment]
Hmmm good point il look into it

**Comment by iholston** [comment]
should be good to go, if you want different framerates change line 85 in game.cfg

> FrameCapType=3

to 3,4,5,6,7,etc.. 3 is 25, 4 is 30, and so on based on the fps options in the dropdown in the game settings menu...

**Comment by damare1** [comment]
thank you!
