### ISSUE TITLE
Screen size issue after deleting the bot

### ISSUE THREAD

**Issue by Divyam1000** [iholston/lol-bot#71]
Even after deleting all the bot files the game dosent return to its orignal screen size and the fps is still at 25. What could be the problem?

**Comment by iholston** [comment]
There is a file:

C:\Riot Games\League of Legends\Config\game.cfg

That controls the in-game settings. When the bot runs it overwrites this file to get the specific settings the bot needs. To change it back, you can either:

1) Make a backup copy of the file before the bot runs and replace it when the bot is done running 
2) Simply use the in-game settings menu to change the settings back. The game will update the game.cfg file itself

The bot does not replace the file on its own at the moment. Though I may consider adding that in the future...
