### ISSUE TITLE
league of legends path is diffrent

### ISSUE THREAD

**Issue by alperen2311** [iholston/lol-bot#72]
my lol path is not at C:/Riot Games/League of Legends/Config/game.cfg can i change the code this is not working and no space at c disk

**Comment by alperen2311** [comment]
[16092023_0354_log.log](https://github.com/iholston/lol-bot/files/12629519/16092023_0354_log.log)

**Comment by iholston** [comment]
its in the read.me, you need to update the variable in constants.py
