### ISSUE TITLE
Premission denied

### ISSUE THREAD

**Issue by IShadow06** [iholston/lol-bot#74]
![image](https://github.com/iholston/lol-bot/assets/117581041/3ac50025-353d-49bc-95ee-b9ea55b69fcb)
has anyone ever had this error or know how to fix it?

**Comment by iholston** [comment]
Is your league of legends path correct? Where is league of legends installed on your machine?

**Comment by iholston** [comment]
Any update on this @IShadow06 ? Try downloading the latest version (v1.3.1) and see if this is still an issue.

**Comment by IShadow06** [comment]
Oh hey im sorry i completly forgot about this post i made, i just tried to reinstall lol it might have been a path issue i was just not able to fix it by changing path, might have done something wrong but yea its fixed im sorry.

**Comment by iholston** [comment]
Lol no worries. Thanks for the update.
