### ISSUE TITLE
what to do know

### ISSUE THREAD

**Issue by TarkyXD** [iholston/lol-bot#80]
![image](https://github.com/iholston/lol-bot/assets/145849410/159737a3-6258-4cf6-a98c-90ff15afc3dc)

help i dont know what to do now ngl :D

**Comment by AndreMonteiro98** [comment]
same problem here

**Comment by iholston** [comment]
I'm not sure what this says

**Comment by TarkyXD** [comment]
Its saying, that i couldnt find python

**Comment by iholston** [comment]
yea ur gonna need to install python. follow the instructions on the readme

**Comment by TarkyXD** [comment]
can you actually go with me on discord, and ill screen share, bcs i dont know what i am doing wrong, i install python and i select to be in PATH, then i am following the setup, and it says: that it cant find the python

**Comment by TarkyXD** [comment]
> can you actually go with me on discord, and ill screen share, bcs i dont know what i am doing wrong, i install python and i select to be in PATH, then i am following the setup, and it says: that it cant find the python

i can use the: Installer.bat, but when i open: Launcher.bat it shows me the same thing.

**Comment by iholston** [comment]
I don't do much setup help or discord. I can discuss here but that's about it. I would recommend watching a youtube video on how to install python. It seems like your python is probably not on your PATH.

**Comment by TarkyXD** [comment]
> I don't do much setup help or discord. I can discuss here but that's about it. I would recommend watching a youtube video on how to install python. It seems like your python is probably not on your PATH.

Okay, I did that and also I did setup the enviroment variables, and it still doesnt work, it still say's, that it couldnt find python

**Comment by iholston** [comment]
I'm sorry my friend. I don't know what else to try for you. Let me know if you figure it out though.

**Comment by iholston** [comment]
I've added this video to the readme but this https://www.youtube.com/watch?v=uDbDIhR76H4 might help. Also, once you install it, you will need to close and reopen CMD. @TarkyXD
