### ISSUE TITLE
Stop at Results Screen

### ISSUE THREAD

**Issue by damare1** [iholston/lol-bot#88]
Hi.
I am using BOT on a desktop PC (Ryzen5 5600G,16GBMemory) and a laptop (i5-4210U 4GBMemory).
The desktop is working fine.
On the laptop, the bot sometimes stops at the results screen.
The log shows that it stops at [MID/LATE GAME ROTATION] and does not go to [EXIT].
Is this due to low specs?
https://i.imgur.com/vLuB7Tb.png

**Comment by iholston** [comment]
No this is due to a bug I believe, try the newest version of the bot (currently 1.3.0) and see if you still have this issue.

**Comment by damare1** [comment]
Thanks for the quick response.
I will use 1.3.0. I will report back.

**Comment by damare1** [comment]
I downloaded 1.3.1 and tried to use it, but it's impossible.
It keeps forcing me to quit and reconnect at the load screen.
This error also occurred in v1.2.1.
I can use v1.1.1 with no problems, so I continue to use this.

**Comment by iholston** [comment]
Hmm that is odd. If you have time, in the 1.3.0 version change ```LOGGING_LEVEL``` in constants.py to 
> LOGGING_LEVEL = logging.DEBUG 
and run it again. Once the error goes through just drop the latest log from the /log folder in here so i can see.

**Comment by iholston** [comment]
Although, is the bot trying to play the tutorial?

**Comment by damare1** [comment]
No. The game mode is beginner (830).

**Comment by damare1** [comment]
Log file.
[dotup.org3053641.log](https://github.com/iholston/lol-bot/files/12741025/dotup.org3053641.log)

**Comment by damare1** [comment]
Log file.
[28092023_0130_log.log](https://github.com/iholston/lol-bot/files/12741032/28092023_0130_log.log)

**Comment by iholston** [comment]
This is great, thank you. I think i may know the issue, hopefully I'll get a hotfix out and release v1.3.1 today.

**Comment by damare1** [comment]
Thank you. I hope this issue will be resolved.

**Comment by iholston** [comment]
I think the issue should be solved with v1.3.1, if not please let me know.

**Comment by Akihoma** [comment]
@iholston Is it possible to make it so that, to begin with, he played 3 game tutorials on new accounts?

**Comment by iholston** [comment]
the bot cannot play the tutorials, the tutorials should simply be skipped.

**Comment by damare1** [comment]
Thanks. I was able to connect.(v1.3.1)
I will now verify if it stops at the Results screen.

**Comment by iholston** [comment]
@damare1 it looks like your client is not in English, if this is the case. Can you confirm whether or not the bot is actually purchasing items in v1.3.1? This is related to #89

**Comment by damare1** [comment]
Also available in Japanese.
![ddd](https://github.com/iholston/lol-bot/assets/144917228/509bad8a-86ad-43fc-b524-145098b23127)
My account using v1.3.1↓.
https://www.op.gg/summoners/jp/FlashHeal
However, I am doing this in game mode 830, so item purchases are done automatically upon exiting the fountain.
No item purchase is required for 830 users.

I used v1.3.1 for a day and it kept working without stopping at the results screen.
I am happy about this. It usually stopped 1-3 times a day.
Thank you.
