### ISSUE TITLE
buying items

### ISSUE THREAD

**Issue by acng7** [iholston/lol-bot#89]
the item overhaul is cool and all but when u leave the fountain the game automatically buy the right items for u so is buying the item urself actually necessary?

**Comment by iholston** [comment]
I'm not aware of the game buying items for you. Which mode is this?

**Comment by acng7** [comment]
im currently q-ing intro, the game will buy items for u when u have 1,5k+ gold, plus i think searching for items name wouldnt work if the game isnt in english

**Comment by iholston** [comment]
You bring up a good point with the languages, I may have to revert it back to clicking tbh. But in beginner and intermediate  bots I don't think the game buys for you. Il look into it this weekend.

**Comment by iholston** [comment]
This should be fixed with the latest couple versions, the bot no longer relies on any particular language to purchase items.
