### ISSUE TITLE
utf-8 Error

### ISSUE THREAD

**Issue by GamerGoiano666** [iholston/lol-bot#9]
**I got this error after trying to use my database**
  File "C:\Users\Maquina\Desktop\Bot de upar contas em Python\scripts\bot.py", line 28, in main
    client.init()
  File "C:\Users\Maquina\Desktop\Bot de upar contas em Python\scripts\client.py", line 37, in init
    start_app(username, password)
  File "C:\Users\Maquina\Desktop\Bot de upar contas em Python\scripts\client.py", line 263, in start_app
    log.info(str(output, 'utf-8').rstrip())
             ^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 0: invalid continuation byte

**The accounts.py updated:**
`import random
import mysql.connector

# Configuração da conexão com o banco de dados
db_config = {
  'host': '192.168.1.8',
  'user': 'goiano',
  'password': 'goiano',
  'database': 'contas',
  'charset': 'utf8'
}

cnx = mysql.connector.connect(**db_config)

def get_username():
    # Conexão com o banco de dados
    cnx = mysql.connector.connect(**db_config)
    # Cursor para executar as consultas SQL
    cursor = cnx.cursor()
    # Consulta SQL para obter uma conta aleatória com nível menor que 30
    query = ("SELECT login FROM upando WHERE nivel < 30 ORDER BY RAND() LIMIT 1")
    cursor.execute(query)
    result = cursor.fetchone()
    # Fechar a conexão com o banco de dados
    cursor.close()
    cnx.close()
    return result[0] if result else None

def get_password():
    # Conexão com o banco de dados
    cnx = mysql.connector.connect(**db_config)
    
    # Cursor para executar as consultas SQL
    cursor = cnx.cursor()
    # Consulta SQL para obter uma conta aleatória com nível menor que 30
    query = ("SELECT senha FROM upando WHERE nivel < 30 ORDER BY RAND() LIMIT 1")
    cursor.execute(query)
    result = cursor.fetchone()
    # Fechar a conexão com o banco de dados
    cursor.close()
    cnx.close()
    return result[0] if result else None

def set_account_as_leveled():
    # Conexão com o banco de dados
    cnx = mysql.connector.connect(**db_config)
    # Cursor para executar as consultas SQL
    cursor = cnx.cursor()
    # Consulta SQL para atualizar a conta para nível máximo
    query = ("UPDATE upando SET nivel = 100 WHERE login = %s")
    # Obter um nome de usuário aleatório e atualizar o registro correspondente
    username = get_username()
    cursor.execute(query, (username,))
    cnx.commit()
    # Fechar a conexão com o banco de dados
    cursor.close()
    cnx.close()`

**Comment by GamerGoiano666** [comment]
The bot use a account from database but after login, i got the utf-8 error :/
Could u tell me how to use database connection with your bot?
I am using MySQL from XamPP

**Comment by iholston** [comment]
I would simply comment out line 263 in client.py and see if it works.

**Comment by GamerGoiano666** [comment]
> I would simply comment out line 263 in client.py and see if it works.

It worked <3, if you want, i am using mysql from xampp, u can edit your code to mine if you want, it is working fine.
