### ISSUE TITLE
Python Installation Issues

### ISSUE THREAD

**Issue by DjoleJedeGovna** [iholston/lol-bot#90]
C:\Users\Korisnik\Downloads\lol-bot-main\lol-bot-main\scripts>python main.py
'python' is not recognized as an internal or external command,
operable program or batch file.

I've installed both python 3.11 and pyautogui, I dont know whats the problem

![image](https://github.com/iholston/lol-bot/assets/146292170/5a28d1f8-dc7d-4d25-b27b-84424d71c377)

**Comment by iholston** [comment]
Did you add python to your system path? It's a checkbox when you install. If not try double clicking on main.py in the scripts folder.

**Comment by DjoleJedeGovna** [comment]
I did both, looked it up on google and it told me to do it manually in the "Environment Variables" file and I did it there too
I've done it in both PATHs. 
![image](https://github.com/iholston/lol-bot/assets/146292170/5e66529a-6600-46c2-85e1-7a57b9c614df)
![image](https://github.com/iholston/lol-bot/assets/146292170/3bbfa30e-d44f-4f21-b21a-4ac0ceb131ed)
![image](https://github.com/iholston/lol-bot/assets/146292170/6fec2f23-37c7-4ef1-94e3-8ad09d6c1740)

**Comment by iholston** [comment]
Yea not really sure here, maybe try right clicking on main.py in the scripts folder and click run with python or something like that.

**Comment by iholston** [comment]
Also, usually python is installed into Program Files, it should be installed somewhere like 

> C:\Program Files\Python311\
> C:\Program Files\Python311\Scripts\

**Comment by iholston** [comment]
Did you actually use the python installer?

**Comment by DjoleJedeGovna** [comment]
In the end i just had to reinstall python, everything works well now. Thank you for your help
