### ISSUE TITLE
Wont start says script is paused or something

### ISSUE THREAD

**Issue by lolboter** [iholston/lol-bot#91]
heres what it says 
![image](https://github.com/iholston/lol-bot/assets/146392091/8edd44dd-a704-495e-8587-067403c899e8)
and heres what is says when i run the launcher as administrator
![image](https://github.com/iholston/lol-bot/assets/146392091/1be91f14-6f4b-4119-8c9d-a4264390f974)

help please man i did everything u said on instaling the python launcher correctly

**Comment by iholston** [comment]
Brother, you simply need to double click on launcher.bat

**Comment by lolboter** [comment]
> Brother, you simply need to double click on launcher.bat

i legit double click on launcher and it says this 
![image](https://github.com/iholston/lol-bot/assets/146392091/e57c3472-c310-4205-a094-7e4a214af2d1)

**Comment by iholston** [comment]
Then double click on main.py

**Comment by lolboter** [comment]
> Then double click on main.py

i did  and  it did nothing still says 
![image](https://github.com/iholston/lol-bot/assets/146392091/8026cc97-f65f-4808-99a8-e6fad0b7139b)
i really dont know what to do i tried reinstaling python and it also did nothing im really stuck

**Comment by iholston** [comment]
are there log outputs in the logs.py folder? paste them here.

**Comment by lolboter** [comment]
> are there log outputs in the logs.py folder? paste them here.

cant find logs,py folder

**Comment by iholston** [comment]
No there should be a folder called logs not logs.py

**Comment by iholston** [comment]
No it's fine, go to the folder with the code and see if there is a logs folder

**Comment by lolboter** [comment]
> No it's fine, go to the folder with the code and see if there is a logs folder

I went to the folder with the code and theres no logs folder :(

**Comment by iholston** [comment]
Yea I'm not sure what to tell you my friend . What happens when you double click on main.py? send a screenshot of that.

**Comment by iholston** [comment]
did you move the launcher.bat out of the original folder that it was in?

**Comment by iholston** [comment]
It should look like the gif from the readme when you start it.

**Comment by lolboter** [comment]
> did you move the launcher.bat out of the original folder that it was in?

I didnt move it from the original folder

**Comment by lolboter** [comment]
> It should look like the gif from the readme when you start it.

Yea i know but it doesnt look like that

**Comment by lolboter** [comment]
> Yea I'm not sure what to tell you my friend . What happens when you double click on main.py? send a screenshot of that.

I cant screenshot it bcs it happens so fast.. i click on main.py and it does something very fast and closes...

**Comment by lolboter** [comment]
and now it wont even open the installer.... 
![image](https://github.com/iholston/lol-bot/assets/146392091/ae001915-0552-49e2-b523-05f01f888806)

**Comment by iholston** [comment]
no you shouldn't be typing python installer. It should look like this https://user-images.githubusercontent.com/32341824/231916860-8cdaa0bb-c808-48f7-8afe-5cd151501a98.gif

**Comment by lolboter** [comment]
but the problem is when i dont type pyhton installer and just clikc on installer it wont open

**Comment by iholston** [comment]
try clicking and running launcher.bat as administrator. Installer is .bat file so typing 'python installer' won't do anything.

**Comment by lolboter** [comment]
> try clicking and running launcher.bat as administrator. Installer is .bat file so typing 'python installer' won't do anything.

Tried running it as administrator and it now it gives me the cant find directory error...

**Comment by iholston** [comment]
okay so as the readme states. you need to update the constants.py file with the path to your league of legends directory.

**Comment by lolboter** [comment]
> okay so as the readme states. you need to update the constants.py file with the path to your league of legends directory.

I did it just now and now launcher wont even open...anyhow i give up man ty for trying to help me
