### ISSUE TITLE
Invalid Start Byte

### ISSUE THREAD

**Issue by iWeren** [iholston/lol-bot#92]
The bot logs in and opens the game but when the client opens it throws an automatic error that says: [ERROR ] [account_loop ] 'utf-8' codec can't decode byte 0xa2 in position 19: invalid start byte, is there a solution for that?

![image](https://github.com/iholston/lol-bot/assets/86067518/0d91a1f8-2240-4f63-81e4-6ce701616c48)

**Comment by iholston** [comment]
What did you change in constants.py?

**Comment by iholston** [comment]
Drop the latest log in logs.py

**Comment by iWeren** [comment]
[29092023_0033_log.log](https://github.com/iholston/lol-bot/files/12772794/29092023_0033_log.log)

**Comment by iholston** [comment]
Okay, this is a bug. I have uploaded a fix for it and should push out a new version here shortly.
