### ISSUE TITLE
Invalid Username/Password

### ISSUE THREAD

**Issue by thuypoi** [iholston/lol-bot#95]
![image](https://github.com/iholston/lol-bot/assets/90992052/bd2233f6-01cb-4f30-9760-6e72b9fb9a48)
![image](https://github.com/iholston/lol-bot/assets/90992052/6dd6cd1c-c4cb-4826-90e3-a511cd5d3103)

Pls help.I can not log in

**Comment by iholston** [comment]
All i can say here is to double check the password.

**Comment by iholston** [comment]
Did you replace the accounts.py file in scripts with the one in resources?

**Comment by thuypoi** [comment]
> Did you replace the accounts.py file in scripts with the one in resources?

i did it
 password is oke
 sorry my english bad

**Comment by iholston** [comment]
I don't know what is wrong then. If you replaced the accounts.py file in /scripts with the one in /resources, then all I can tell you is to manually log in and then start the bot.

**Comment by thuypoi** [comment]
![image](https://github.com/iholston/lol-bot/assets/90992052/c4bcdf08-21a9-4efe-9647-e40257e0fb47)
I change is here and it work^^
thanks for care
