### ISSUE TITLE
idk how to describe this

### ISSUE THREAD

**Issue by iWeren** [iholston/lol-bot#96]
the game launchs and instantly throw this error
![image](https://github.com/iholston/lol-bot/assets/86067518/c6336cf8-fe6f-4dd1-ab5f-c210d471c1e5)
[01102023_0205_log.log](https://github.com/iholston/lol-bot/files/12776272/01102023_0205_log.log)

**Comment by iholston** [comment]
Hmm il have to look into this, for some reason it cannot connect to the league of legends local server. Try running the bot when league is already opened
