### ISSUE TITLE
Staying under mid turret

### ISSUE THREAD

**Issue by jibaaRK** [iholston/lol-bot#97]
The bot automatically lock tristana, then buy doran ring and after that he goes mid under the turret and never leave it or hit a minion.

How can i solve it ?

**Comment by iholston** [comment]
send the latest log in the log folder.

**Comment by jibaaRK** [comment]
[01102023_1647_log.log](https://github.com/iholston/lol-bot/files/12777756/01102023_1647_log.log)

i started playing by myself after a few times

**Comment by jibaaRK** [comment]
Also, i just installed it today. So i can't say for the previous release but for me, on this one, it's not working. The bot is also opening the shop under the tower, typing "doran ring".
I think i followed all the instructions to install it. add python to path, etc

**Comment by iholston** [comment]
Is ur game window 1024x720?

**Comment by jibaaRK** [comment]
Yes

I also tried to shut down my second screen, it doesnt change anything

**Comment by iholston** [comment]
Do you have custom hotkeys?

**Comment by iholston** [comment]
If attack move click is not enabled and on the default key bind the bot will not move.

**Comment by jibaaRK** [comment]
Oh, i tought the bot reseted the hotkey, i'ma try that

**Comment by jibaaRK** [comment]
[02102023_1051_log.log](https://github.com/iholston/lol-bot/files/12781465/02102023_1051_log.log)
 
Ok far better right now ! Still some little issues : 
-not leveling some spells
- buying full doran shields on tristana
- Tp'ed on the tower and back to base after
But at least, it works, thanks a lot for you work 👍

**Comment by acng7** [comment]
> [02102023_1051_log.log](https://github.com/iholston/lol-bot/files/12781465/02102023_1051_log.log)
> 
> Ok far better right now ! Still some little issues : -not leveling some spells
> 
> * buying full doran shields on tristana
> * Tp'ed on the tower and back to base after
>   But at least, it works, thanks a lot for you work 👍

The bot just buys items randomly based on a set list of items, all u need is the bot doing the tedious part of leveling ur accounts, it doesnt have to do it intelligently 💀
